### ISSUE TITLE
treeseq/tests cause segfault with SLiM 3.5 

### ISSUE THREAD

**Issue by hyanwong** [MesserLab/SLiM#132] opened 2021-01-08 23:14 UTC
Running `./run_tests.sh` from within the `SLiM/treeseq/tests` directory currently results in a segfault (tested on both OS X and linux), outputting the following to `SLiM_run_output.log`

```
// Initial random seed:
22

// RunInitializeCallbacks():
initializeSLiMModelType(modelType = 'nonWF');
#WARNING (Eidos_ExecuteFunction_paste): function paste() changed its semantics in Eidos 2.5 (SLiM 3.5).  The second argument here is no longer interpreted to be a separator string; if you want those semantics, use 'sep=' to name the second argument, as in 'paste(1:5, sep=",");'.  That is the way to regain backward compatibility.  If, on the other hand, you do not intend the second argument here to be a separator string, you can get rid of this warning by appending the second argument using the + operator instead.  For example, you would transform 'x = paste(1:5, ",");' into 'x = paste(1:5) + " ,";'.  You can also use suppressWarnings() to avoid this warning message.
#WARNING (Eidos_ExecuteFunction_paste): function paste() changed its semantics in Eidos 2.5 (SLiM 3.5).  The second argument here is no longer interpreted to be a separator string; if you want those semantics, use 'sep=' to name the second argument, as in 'paste(1:5, sep=",");'.  That is the way to regain backward compatibility.  If, on the other hand, you do not intend the second argument here to be a separator string, you can get rid of this warning by appending the second argument using the + operator instead.  For example, you would transform 'x = paste(1:5, ",");' into 'x = paste(1:5) + " ,";'.  You can also use suppressWarnings() to avoid this warning message.
```

I think this is @petrelharp 's domain?

**Comment by bhaller** [comment] 2021-01-08 23:22
Fix should be trivial, just give a "sep=" prefix to the separator argument to `paste()` in your script.  You might also want to fix whatever test harness bug is causing it to segfault, though.  :->

**Comment by petrelharp** [comment] 2021-01-09 04:35
Hm, nope - it's something else. To reproduce, make these three files:
`test.slim`:
```
initialize() {
    source("load_A.slim");
}
```
`load_A.slim`:
```
source("load_B.slim");
```
and, `load_B.slim`:
```
catn("hello!!!");
```
Then, running
```
slim test.slim
```
produces
```
// Initial random seed:
2911976834525

// RunInitializeCallbacks():
#WARNING (Eidos_ExecuteFunction_paste): function paste() changed its semantics in Eidos 2.5 (SLiM 3.5).  The second argument here is no longer interpreted to be a separator string; if you want those semantics, use 'sep=' to name the second argument, as in 'paste(1:5, sep=",");'.  That is the way to regain backward compatibility.  If, on the other hand, you do not intend the second argument here to be a separator string, you can get rid of this warning by appending the second argument using the + operator instead.  For example, you would transform 'x = paste(1:5, ",");' into 'x = paste(1:5) + " ,";'.  You can also use suppressWarnings() to avoid this warning message.
#WARNING (Eidos_ExecuteFunction_paste): function paste() changed its semantics in Eidos 2.5 (SLiM 3.5).  The second argument here is no longer interpreted to be a separator string; if you want those semantics, use 'sep=' to name the second argument, as in 'paste(1:5, sep=",");'.  That is the way to regain backward compatibility.  If, on the other hand, you do not intend the second argument here to be a separator string, you can get rid of this warning by appending the second argument using the + operator instead.  For example, you would transform 'x = paste(1:5, ",");' into 'x = paste(1:5) + " ,";'.  You can also use suppressWarnings() to avoid this warning message.
hello!!!
Segmentation fault
```

Looks like there's something bad about sourcing files within other files.

**Comment by bhaller** [comment] 2021-01-09 05:21
Wow, nice bug.  The immediate bug is just a dumb thing I did with source() in 3.5.  The crash, however, is a bug in Eidos's function argument processing.  I'm impressed.  :->  I'll fix this tomorrow and ping here when it's fixed.

**Comment by bhaller** [comment] 2021-01-09 20:10
The problem is in the recursion, source() calling source().  There is a bug in Eidos's argument processing when a function is called recursively.  Working on it.  It's a bit complicated :->.

**Comment by bhaller** [comment] 2021-01-09 22:59
Just fixed, forgot to note the issue number in the commit.  Closing.

**Closed** 2021-01-10 03:52 UTC
