### ISSUE TITLE
SLiMGUI: recycle button saves script; sometimes "Document has been modified" dialog is wrong

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#273] opened 2022-01-20 13:27 UTC
In the manual, the description of the "recycle" button is:
```
Recycle: This resets SLiM back to the initialization stage of the simulation. Recycling
also clears the output pane, and re-parses the script in the script pane (which cannot
happen while you’re in the middle of executing a script). Whenever you change your
script, you will need to recycle for your changes to take effect.
```

However (on my machine), if I
1. open a script
2. make a change to it, carefully *not* saving the change, and
3. hit the "recycle" button,

then the changes are in fact saved - the file on disk is modified with the changes, as soon as I hit the "recycle" button. Incidentally, in my testing, usually I can then quit SLiMGUI without the "Document has been modified" dialog popping up.

I sometimes want to modify scripts temporarily, just to test something out, without saving the changes.

However (and maybe one reason I hadn't noticed before?), often when I quit the "Document has been modified" dialog pops up even if I've *just* saved the file, and I know for sure it hasn't been modified. I notice this happens sometimes after using the recycle button as well. (perhaps that should be a different issue, though I don't know how to replicate it)

**Comment by bhaller** [comment] 2022-01-20 17:02
In the SLiMgui preferences panel, it sounds like you have "Autosave on every recycle" checked.  All you should need to do is uncheck that preference.  :->  That's for the first issue.  For the second, I don't know; sounds like something is dirtying your document at a time when you don't expect that to happen, which might be a bug in either SLiMgui or maybe in Qt on Debian.  File a separate issue for that if you find a reproducible case.  When it happens, you might also try looking at the title of the Undo menu item; it might indicate the last operation performed, by name, which might tell you why the document got dirtied.  Anyhow, closing this issue since I think it's just a matter of your prefs setting; if that doesn't resolve the problem, let me know.

**Closed by bhaller** 2022-01-20 17:02 UTC

**Comment by petrelharp** [comment] 2022-01-22 15:50
> In the SLiMgui preferences panel, it sounds like you have "Autosave on every recycle" checked. All you should need to do is uncheck that preference. 

Hah, why so I did. I had certainly never set that - it must be the default? I would vote to make this *not* the default, because (a) for some users this is very surprising and would lead to bad things, and (b) for users that expect it, the worst that happens is that they get the "document unsaved" dialog when quitting?

**Comment by bhaller** [comment] 2022-01-22 23:44
No, the default is off, not on, for the reason (a) that you say – although to be fair, with it off "the worst that happens" is that they manage to hang/crash SLiMgui and they lose all of the unsaved changes they have made to their script.  So there's that.  :->  I tend to think most users ought to run with autosave on most of the time, to avoid that possibility.  But the default is nevertheless off, since autosaving like that is off my default in pretty much all apps.

**Comment by bhaller** [comment] 2022-01-22 23:46
Now of course, if you do a clean install of Linux, and a clean build of SLiMgui, and you find that the default is on, then that's a bug.  But I'd be very surprised; I just checked the coe, and it is quite straightforward; I don't see much latitude for a bug to exist.
