### ISSUE TITLE
working directory in qtslim

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#76] opened 2020-03-29 18:21 UTC
It looks like, from the error messages:
```
willExecuteScript: Unable to set the working directory to  /home/peter/Desktop  (error  2 )
```
that even if I start qtslim from the command line, it tries to set its working directory to ~/Desktop. It produces the same message every time I hit the 'recycle' button, also. (It gives me an error message rather than just setting it beause I don't have a ~/Desktop directory.)

I think that ~/Desktop is a reasonable default for the working directory if SLiM is started from the GUI, but if started from the command line then it should stick to the working directory it inherits from there. (So, if I run `qtslim` from the directory ~/my/slim/work, then SLiM's working directory should be ~/my/slim/work unless it is told otherwise - this is in fact true already on my system since SLiM tries to reset it to the Desktop but fails.) It's also probably harmless that it tries to reset working directories various times, but a little worrisome - it should just be able to fix it at the start if it's some wierd GUI-related directory, then leave it along.

**Comment by bhaller** [comment] 2020-03-29 19:08
OK, so it seems to me there are three separable issues here:

(1) QtSLiM switches between working directories a lot.

(2) ~/Desktop doesn't exist on your machine and that results in logs.

(3) You want the default directory to be whatever the command-line path is when you launch QtSLiM from the command line.

Taking these one at a time:

(1) Yes, it does.  :->  The main reason for this is that you can have multiple model windows open, with a different working directory set for each, and you can press play in more than one of those windows at once.  (This mostly works now, although I think there's a bug in there somewhere that makes the results less than 100% correct.)  So to make this work, QtSLiM (and SLiMgui) changes the WD to the model's WD whenever it's about to call out to the SLiM engine to run a generation, and then changes it back when the SLiM engine returns.  It does a similar thing with other model-specific state, like the RNG, to keep each model independent of what's happening in the others.  There's no particular reason to do this only when the user is running multiple models simultaneously; it's a sensible design in general, to make each model self-contained, and so it is done always.  So I think (1) is not a bug.

(2) I'm not sure what to think about this.  Is it normal not to have a ~/Desktop directory on Linux?  It seems to exist on my Ubuntu install; I was figuring it's a standard thing, as it is on macOS.  Does Debian not have one by default, or did you delete it for some reason?  Qt provides the "desktop directory" via a class they provide, QStandardPaths; I just use that class and do what it tells me to do.  I don't really want to get into special-casing Debian or something, unless absolutely necessary – that way lies madness.  Besides QStandardPaths::DesktopLocation, Qt provides QStandardPaths::DocumentsLocation (~/Documents on Linux) and QStandardPaths::HomeLocation (~ on Linux); do you think one of these would be more appropriate?  Defaulting to ~ seems poor – almost never what the user wants.  If ~/Documents is universal across Linux flavors, maybe it's better than the desktop?

(3) Hmm.  Is it normal/typical for users to launch GUI apps from the terminal on Linux?  That is extremely uncommon on macOS.  Do you know how I would tell whether the app was launched from the terminal, in order to draw this distinction?  I'm not necessarily opposed to this idea in principle, but it feels pretty weird to me – it feels like the behavior of an app should not depend upon whether the app was launched one way or another way.  An app should provide consistent behavior, period; and if you want the WD to be different for a given run of the app you can always click the button that lets you change it (although I realize that might be onerous if you're having to do it constantly).  I'm willing to be talked into this; but I also don't know how to implement it anyway.  Googling "how to tell whether an app was launched from the terminal linux" produces nothing useful.  I don't know whether the OS even provides this information.

**Comment by petrelharp** [comment] 2020-03-29 21:35
(1) Ah, I see. I guess I imagined one process per window or something, but this makes sense.

(2) I don't think this is a bug. The error message is no problem, and nothing wierd happens.  That's just why I could tell what qtslim was doing. =)

(3) 
>  Is it normal/typical for users to launch GUI apps from the terminal on Linux?

Yes, reasonably. For instance, if I want to open up a docx file, I might do `libreoffice thefile.docx` in whatever directory `thefile.docx` is in. Or `rstudio myscript.R`, which will keep the working directory at whatever it was when you opened it.  For me, it feels wierd that the behavior of a program might *not* depend on where you launched it from. =)

> Do you know how I would tell whether the app was launched from the terminal

Well, the working directory is *something* when it is started; on my computer it looks like it is set to ~ if I launch from the GUI. Maybe a good default on linux is not to set it to anything - just keep it as is?

**Comment by bhaller** [comment] 2020-03-29 21:44
OK, so let's forget about (1) and (2).

Regarding (3).  On macOS the default WD is actually the folder inside the app bundle where the executable resides, for whatever ridiculously stupid reason.  That is obviously unacceptable as a WD, which is why SLiM (and now QtSLiM) explicitly set the WD to the desktop; it seemed like a reasonable choice of default (and I wasn't expecting it not to exist on some user's machines!).  All else being equal, I'd prefer that the behavior be the same across platforms, so that when people (like me) move between Mac and Linux they don't have to think about platform-specific differences in behavior; I've been trying to make the user experience as parallel as possible across platforms.  So defaulting to the desktop on Linux still seems fine and right to me – except that it doesn't exist sometimes apparently.  (Do you know whether that's a Debian thing, or what?)  And I'd be OK with using the current WD when launched from Terminal – if I can tell when that happens, and ideally make SLiMgui do the same on the Mac for consistency.

**Comment by petrelharp** [comment] 2020-03-29 21:59
> I'd be OK with using the current WD when launched from Terminal – if I can tell when that happens, and ideally make SLiMgui do the same on the Mac for consistency.

That'd be good. I have no idea how to do it, though. Perhaps you can check the environment variables to see if it's [an interactive shell?](https://www.tldp.org/LDP/abs/html/intandnonint.html) 

> Do you know whether that's a Debian thing, or what?

I deleted it, that's why it doesn't exist. =)

**Comment by bhaller** [comment] 2020-03-29 22:20
> > I'd be OK with using the current WD when launched from Terminal – if I can tell when that happens, and ideally make SLiMgui do the same on the Mac for consistency.
> 
> That'd be good. I have no idea how to do it, though. Perhaps you can check the environment variables to see if it's [an interactive shell?](https://www.tldp.org/LDP/abs/html/intandnonint.html)

Hmm, interesting.  I'll look into that.

> > Do you know whether that's a Debian thing, or what?
> 
> I deleted it, that's why it doesn't exist. =)

Ah.  That is useful information; now I'm less worried about this being some weird Debian-specific problem.  :->  So... you don't like desktops, eh?  :->

**Comment by grahamgower** [comment] 2020-03-30 06:37
~/Desktop never existed on unix until (I think) Fedora and Ubuntu linuxes popularised it. The freedesktop.org folks tried to standardise this. But many linux systems consider GUIs to be optional, and won't have a ~/Desktop by default. There are many GUI environments available for unix systems, some have a notion of a "desktop" and some don't. Some GUI environments will create the ~/Desktop folder if it doesn't already exist. Actually, the folder name is just a convention, and could be configured to be anything (https://freedesktop.org/wiki/Software/xdg-user-dirs/).

I'll be honest, I never quite understood what the ~/Desktop folder was supposed to be useful for. Like Peter, I tend to delete it if I ever see it in my $HOME. Its always empty on my systems after all.

**Comment by bhaller** [comment] 2020-03-30 14:34
Interesting.  Linux people are different from Mac people.  :->

**Comment by petrelharp** [comment] 2020-03-30 16:22
> Interesting. Linux people are different from Mac people. :->

Yeah - whether their favorite interface is the mouse or the keyboard?

**Comment by bhaller** [comment] 2020-04-03 17:13
Hi @petrelharp.  I have just done a commit that I believe fixes this issue.  However, I'm unable to test it because I'm unable, on macOS at least, to build a standalone app for QtSLiM that I can launch from Terminal; I'm being bitten by a linker issue that I haven't resolved yet (https://stackoverflow.com/questions/11676062/qt-app-finds-libraries-when-launched-from-qtcreator-but-not-from-command-line), and so I can only run QtSLiM from inside Qt Creator.  Sigh.  I really, really hate makefiles and linkers.  I'd test it on Ubuntu, but my good machine for running Ubuntu is in the lab at Cornell, which we're not really supposed to go to right now.  I take it you're able to build a standalone app on Debian, just with qmake/make, without link issues?  I wonder if that's because Linux is better behaved, or because the newer Qt you're using has fixed the linker problem in question?  I think I'm going to install the latest Qt on my wife's machine so I can test things against it.  :-O

So.  I think it's fixed.  (1) Launching from a shell should cause QtSLiM to use the shell's current working directory as its default directory.  (2) When launched from a not-shell, QtSLiM will still try to use ~/Desktop by default, but it will check for the existence of that directory, and if it doesn't exist it will fall back on ~.  So those logs you were seeing should be gone, and it should use ~ for you in that case.

Please test and report back, since I can't.  Thanks!

**Comment by petrelharp** [comment] 2020-04-04 17:00
Yes, it works - launching from the shell keeps the directory it was launched from as the working directory. When I started it from the GUI, the working directory was my home directory.

>  I take it you're able to build a standalone app on Debian

Yes - I just did
```
mkdir qtbuild
cd qtbuild
cmake -DBUILD_QTSLIM=ON ..
make
```
thanks to the very nice cmake rules!!

> but my good machine for running Ubuntu is in the lab at Cornell,

You could `ssh -X` to it? Oh, I don't know if that works on OSX.

**Comment by bhaller** [comment] 2020-04-04 17:19
> Yes, it works - launching from the shell keeps the directory it was launched from as the working directory. When I started it from the GUI, the working directory was my home directory.
> 
> Thanks!!

Awesome.  So this issue can be closed now, right?  Or is there anything left over for it?

> > I take it you're able to build a standalone app on Debian
> 
> Yes - I just did
> 
> ```
> mkdir qtbuild
> cd qtbuild
> cmake -DBUILD_QTSLIM=ON ..
> make
> ```
> 
> thanks to the very nice cmake rules!!

OK, groovy.

> > but my good machine for running Ubuntu is in the lab at Cornell,
> 
> You could `ssh -X` to it? Oh, I don't know if that works on OSX.

Cornell has a firewall that gets in the way.  Cornell IT really does everything they possibly can to get in the way of work getting done.  They also won't let me have my desktop and laptop on the same network, so to transfer files between them I have to cable them directly together.  And they try to force me to upgrade my machine when I don't want to (but I've figured out a way to snooker them on that one).  And... oh, I could tell you stories.  :->

**Comment by petrelharp** [comment] 2020-04-04 17:20
> Awesome. So this issue can be closed now, right?

Yep! As far as I can tell.

> to transfer files between them I have to cable them directly together.

omg

**Comment by bhaller** [comment] 2020-04-04 17:20
OK, closing.

**Closed by bhaller** 2020-04-04 17:20 UTC
Labels: qtslim
