### ISSUE TITLE
(potential) issue with nearestNeighborsOfPoint function

### ISSUE THREAD

**Issue by bobweek** [MesserLab/SLiM#298] opened 2022-03-04 17:49 UTC
hello!

im modelling host-parasite coevolution in 2d continuous space with periodic boundaries in both dimensions. to collect the host neighbors that a parasite individual would pick from in attempt to infect, i am making use of the nearestNeighborsOfPoint function. in the case where the parasite fails to infect any of its host neighbors, it receives a fitness penalty. making this penalty high, i see the parasite population collapses, which is fine. however, iterating the simulation step-by-step in the slim gui, i see the collapse begins at the "edges" and the population clusters towards the "center" (even though there should be no such things as edges and centers for periodic boundaries). my hypothesis is that something peculiar is happening with the nearestNeighborsOfPoint function in regards to spatial periodicity, but i really have no clue. i have attached my slim script (saved with a .txt extension because github refuses to attach it with as .slim extension).

[one-causal-locus-mam.txt](https://github.com/MesserLab/SLiM/files/8187851/one-causal-locus-mam.txt)

**Comment by bhaller** [comment] 2022-03-04 18:03
Thanks Bob, I'll look into this.

**Comment by bhaller** [comment] 2022-03-04 20:35
Hi @bobweek.  OK, so I'm running your test model but I'm not sure what I'm looking for.  I see two big spatial populations that don't seem to be doing a heck of a lot, visually speaking; I ran it for a while and nothing much seems to happen.  At what point does the bug manifest?  Could you post a screenshot?

Anyhow, I wrote a little test model for `nearestNeighborsOfPoint()`:

```
initialize() {
	initializeSLiMOptions(dimensionality="xy", periodicity="xy");
	initializeMutationRate(1e-7);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
	
	// Set up an interaction for spatial competition
	initializeInteractionType(1, "xy", reciprocal=T, maxDistance=0.3);
	i1.setInteractionFunction("n", 3.0, 0.1);
}
1 late() {
	sim.addSubpop("p1", 5000);
	
	// initial positions are random in ([0,1], [0,1])
	p1.individuals.x = runif(p1.individualCount);
	p1.individuals.y = runif(p1.individualCount);
}
1: late() {
	// evaluate interactions before fitness calculations
	i1.evaluate();
	
	// test nearestNeighborsOfPoint() using i1
	inds = p1.individuals;
	inds.color = "black";
	testPoint = p1.pointUniform(1);
	near = i1.nearestNeighborsOfPoint(p1, testPoint, 500);
	near.color = "red";
	nearer = i1.nearestNeighborsOfPoint(p1, testPoint, 200);
	nearer.color = "orange";
	nearest = i1.nearestNeighborsOfPoint(p1, testPoint, 10);
	nearest.color = "yellow";
}
fitness(NULL) {
	// spatial competition
	totalStrength = i1.totalOfNeighborStrengths(individual);
	return 1.1 - totalStrength / p1.individualCount;
}
modifyChild() {
	child.setSpatialPosition(p1.pointPeriodic(parent1.spatialPosition + rnorm(2, 0, 0.02)));
	return T;
}
2000 late() { sim.outputFixedMutations(); }
```

It chooses a random point in space each tick, and colors the 500 nearest individuals to that point according to how near they are.  It looks to me like it's doing what I expect with the periodic boundaries, e.g.:

![Constrictor 1](https://user-images.githubusercontent.com/10171101/156837168-7cd6e8a6-ecbb-4bda-b9bc-350cb63c1d2c.jpg)

That shows the neighbors around a point that is near to one of the corners, showing that the nearest neighbors wrap around both periodic boundaries as expected.  Seems fine.  So I suspect that your model might have some other bug, or perhaps the behavior you're seeing was just the result of one particular random number seed's behavior?  Anyhow, if you can provide a simpler reproducible case, or at least tell me more precisely what I'm looking for in this test case, that would be helpful.  I'll leave this open for the time being to wait for your reply, but as far as I can tell there is no bug here.

One question: what version of SLiM are you running?  It is, of course, possible that there was a bug in some older version of SLiM with this stuff; I'd have to dig through old change logs and stuff to find out.

**Comment by bobweek** [comment] 2022-03-04 21:01
hi ben

thanks for taking a look at this!

im using slim 3.7.1

the issue should appear with these parameter values

> defaults = Dictionary(
		"Lh", 500000,
		"Lp", 500000,
		"hSD", 2.0,  			// host dispersal distance	
		"pSD", 2.0,  			// parasite dispersal distance
		"SI", 1.0,  			// spatial interspp interaction distance
		"W", 100.0,  			// width and height of the simulated area
		"ch", 0.1, 			// strength of host competition
		"cp", 0.1, 			// strength of para competition	
		"lmbda", 2.0,		// (spatial) niche breadth
		"h_base", 2.0,		// host base fitness
		"p_base", 1.5,		// para base fitness
		"hc", 0.9, 		        // multiplicative cost on host fitness for each infection
		"pc", 1.0, 			// multiplicative cost on parasite fitness for failing to infect
		"pb", 1.01, 		// multiplicative benefit on parasite fitness for successful infection
		"minpr", 0.2,		// minimum probability of infection (when genotypes don't match)
		"maxpr", 0.9		// maximum probability of infection (when genotypes do match)
		);	

i also ran a test script for a single species and it seemed to behave as expected. so i think there is something weird happening with the interspecific interaction. perhaps it's not an issue with the `nearestNeighborsOfPoint` at all, but rather an issue with my implementation.

thanks again!

**Comment by bhaller** [comment] 2022-03-04 21:21
OK, using those parameter values I was able to reproduce the problem pretty easily.  I think the problem is with your script, yes.  In particular, I notice this code:

0.5*(individual.spatialPosition + mate.spatialPosition)

Note that because of periodic boundaries, an individual and its mate might be adjacent in periodic space, but at opposite sides of the space numerically.  This equation will then place the offspring near the center of the map.  This phenomenon promotes higher density at the center and lower at the edges – making the population collapse tend to be biased towards starting at the edges.  I usually place offspring near just one parent, to avoid this sort of positional bias (which bites you with non-periodic boundaries too, in fact, in a slightly different way); but if you really need to use the mean parental position, you'll need to do some coordinate system math to figure out where that really is.  Perhaps there's a way that SLiM could make that easier for you, with some utility method that handled the wrap-around for you, but it's not immediately obvious to me what the best(i.e., most generally useful) approach for such a utility method would be.  Maybe @petrelharp has an opinion on that.  Anyhow, if there's a feature request in here somewhere, that can be a new issue, so I'm going to close this one.  :->  Happy modeling!

**Closed by bhaller** 2022-03-04 21:21 UTC
