### ISSUE TITLE
removing a subpop creates a trees file that cannot be read back in

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#316] opened 2022-05-15 19:04 UTC
At first I thought this was a new problem, but either I'm confused (hopefully!) or this is a pre-existing bug, because it happens with both `multispecies` and `3.7.1`. Run first this script:
```
initialize() {
	initializeTreeSeq();
	initializeMutationRate(0.0);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}

1 early() { sim.addSubpop("p2", 5); }
5 early() { sim.addSubpop("p1", 5); }
10 early() { p2.setSubpopulationSize(0); }
15 late() { sim.treeSeqOutput("init.trees"); }
```
to produce `init.trees`, and then this script:
```
initialize() {
	initializeTreeSeq();
	initializeMutationRate(0.0);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}

1 late() {	sim.readFromPopulationFile("init.trees");}
20 late() { sim.treeSeqOutput("final.trees"); }
```

This *ought* to work, as we're just saving out the state and reloading it again, but we get this error:
```
ERROR (SLiMSim::__ConfigureSubpopulationsFromTables): population metadata does not parse as a valid JSON string; this file cannot be read.

Error on script line 11, character 5:

   sim.readFromPopulationFile("init.trees");
```
The problem is removing `p2`: if we comment out the `p2.setSubpopulationSize(0);` line, there is no error.  This seems related to #168, and given the number of issues we've had with the input/output bits of populations, it's probably worth writing down the requirements/philosophy about what's in the population table, taking a real good look at the code. I think the philosophy that "it is supposed to only represent the state of things at output time" is a good, consistent one, but it's pretty different than what msprime/demes puts in there, so we need some thinking about consequences.

**Comment by bhaller** [comment] 2022-05-16 16:07
Fixed in `multispecies`.  This turns out to be a trivial fix.  The problem started when tskit started requiring metadata of `"null"` instead of just empty metadata.  There was one case in `WritePopulationTable()` that did not get transitioned over, and was still writing out empty metadata instead of `"null"`.  This will be rare for people to run into, because the removed subpop has to have a larger SLiM id than other subpops that still exist; it needs to be positioned at the _end_ of the population table.  The code for filling out the end of the population table with empty subpops was where the bug is.  Your model removes `p2` and leaves `p1`, and thus triggers the bug – sneaky!  So I'm not too worried about needing to write down requirements/policy, etc., at least not as a result of this bug; this was just a trivial oversight, not anything conceptual/complicated.

**Closed by bhaller** 2022-05-16 16:07 UTC

**Comment by bhaller** [comment] 2022-05-16 16:09
Thanks for the excellent reproducible case, BTW, @petrelharp.  I love it when I have one of those so I can get the problem in the debugger!

**Comment by petrelharp** [comment] 2022-05-16 16:24
Well, glad that was easy!
