### ISSUE TITLE
error message for treeSeqOutput inside of first()

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#325] opened 2022-05-30 07:35 UTC
If you try to do `treeSeqOutput( )` inside of a `first()` block:
```
initialize() {
	initializeTreeSeq();
	initializeMutationRate(1e-7);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}

// create a population of 500 individuals
1 early() {
	sim.addSubpop("p1", 500);
}

2 first() {
sim.treeSeqOutput('out.trees');
}
```
you get an error saying you can't do treeSeqOutput "inside a callback":
![Screenshot from 2022-05-30 00-33-01](https://user-images.githubusercontent.com/1046249/170941067-9a1afdf2-9a6d-43ee-ab5c-2b37895bf961.png)
... however, `first()` is not a callback, it's a stage (I think?). This is very minor, but is easy to fix and could lead to confusion.

**Comment by bhaller** [comment] 2022-05-30 13:08
OK, fixed in `multispecies`, thanks!  I fixed it by removing the error, actually; writing out in a `first()` event should be legal, according to current policy.

There is a bit of an odd situation here, though.  The `readFromPopulationFile()` method currently does not allow you to _read_ a file in a `first()` event.  It feels weird and wrong to me to read a file in a `first()` event; to me, those are kind of intended for pre-planning what will happen in the upcoming tick cycle, setting flags and evaluating interactions and preparing for reproduction and maybe calling `skipTick()` and so forth, rather than for more substantive work like loading in model state from a file.  But it is entirely possible that this is just my personal prejudices, and that I just haven't fully embraced the idea of `first()` events as "just another time in the generation cycle when you can do whatever you want".  I think that makes me uncomfortable particularly because of `skipTick()`, which ought to be called before any substantive work has been done in the current tick cycle; allowing a `readFromPopulationFile()` to happen before `skipTick()` deactivates the species for the rest of the tick feels wrong and even dangerous.  But of course this prohibition is just a tiny band-aid on the problem; models could do all sorts of other things in a `first()` event before calling `skipTick()`, and there's no reasonable way for SLiM to detect or prevent that.  So... maybe it's a bad idea to even try, with `readFromPopulationFile()`.  I dunno.  At present, I guess I've decided "a tiny band-aid is better than no band-aid at all".

I decided to allow _writes_, with `treeSeqOutput()` and all the other output methods, in `first()` events because I can see that that might be a time when one wants to take a snapshot.  But the prohibition on `reading` remains, until such time as I change my mind.  This means that if you write out a `.trees` in a first() event, you will not be able to load it back in in a `first()` event, and if you therefore load it in an `early()` or `late()` event instead, you will get a warning that you loaded the file in a different tick cycle stage than it was saved in.  That seems correct and consistent to me, given the other decisions I've made here, but it's also kind of confusing and weird.  :->

So, I'm not going to close this issue yet, because I'd like to hear your thoughts on all this.  Is the way it is now good?  Or should I allow `readFromPopulationFile()` to be called from `first()` events, even though I personally feel like that is probably a bad idea 99.9% of the time?  Or should I disallow output in `first()` events, to mirror the decision to disallow reads at that time?

**Comment by petrelharp** [comment] 2022-05-31 15:42
Huh, interesting. I had just determined that tree sequences couldn't be written out in `first()` and so I didn't need to worry about that stage in pyslim, which was kinda nice.=)

I guess I think that if you can write out during that stage you should also be able to read in during that stage, since otherwise (as you say) it's weird and confusing. Unless, that is, there's some good reason that will break things in the future?  It sounds to me like you should either disallow reading and writing in it, or allow both of them.

**Closed** 2022-05-31 19:19 UTC
