### ISSUE TITLE
difficulty using readFromPopulationFile in a multispecies slim script

### ISSUE THREAD

**Issue by bobweek** [MesserLab/SLiM#311] opened 2022-05-05 17:50 UTC
hi! im hoping to use msprime to generate initial diversity for a slim model of two coevolving species (using slim 4.0). to do so, im following [the vignette on pyslim's documentation](https://tskit.dev/pyslim/docs/stable/vignette_coalescent_diversity.html) separately for each species (so outputting one tree sequence per species). taking this approach, readFromPopulationFile seems to work fine for the first species, but when applying this for the second species i am getting a `subpopulation p0 has been used already, and cannot be used again` error. to try and avoid this, i inserted an empty row to the second species population table before dumping the tree sequence. however, in slim this returns a `binary population metadata is not the expected length` error. how can i load in initial tree sequences for multiple species? also, i need to use msprime for the "burn-in" as the model depends on the initial genetic diversity in each species.

**Comment by bhaller** [comment] 2022-05-05 18:01
This may be one for @petrelharp.  Peter, how do you set the population id for subpops created on the python side?

**Comment by clwgg** [comment] 2022-05-06 23:26
Hi @bobweek,
My familiarity with the SLiM codebase is somewhat limited, so please take everything I say with a grain of salt, but I think I am able to get your desired setup to work.
SLiM uses a combination of two metadata fields to populate the `subpop_id` from a tree sequence: the first one is the `subpopulation` field of each individual's metadata, and the second one is the `slim_id` of each population's metadata.
When you simulate your initial diversity in msprime and annotate the default metadata with pyslim (`annotate_defaults`), these values will be `0` for all individuals and populations in each of your two tree sequences (i.e. the default).

You can change this by modifying the metadata of one of these tree sequences, like so:
``` python
    ts = tskit.load("second_species.trees")
    tables = ts.dump_tables()

    individual_metadata = [ind.metadata for ind in tables.individuals]
    for md in individual_metadata:
        md["subpopulation"] = 1
    ims = tables.individuals.metadata_schema
    tables.individuals.packset_metadata(
        [ims.validate_and_encode_row(md) for md in individual_metadata]
    )

    tables.populations.clear()
    meta = ts.tables.populations[0].metadata
    meta['slim_id'] = 1
    tables.populations.add_row(meta)

    tables.tree_sequence().dump("second_species-pop1.trees")
```

Please note that if you're simulating mutations in msprime, you probably want to annotate their `subpopulation` metadata field with the correct subpopulation as well -- see also the metadata summary here: https://tskit.dev/pyslim/docs/stable/metadata.html.

I hope this helps!

**Comment by bhaller** [comment] 2022-05-06 23:31
Thanks @clwgg!  I don't know whether your solution will work or not, since I'm no good in Python, but it certainly looks helpful.  :->  I would note that even if it *does* work perfectly, the complexity of it perhaps indicates that there is room for improvement here.  Trying to import multiple subpops into SLiM as different species will probably be a pretty common thing for people to do,now that SLiM is going multispecies.  So it would be great to make this smoother/easier.  Not sure what the right approach might be for that, though.  So I think perhaps this issue ought to remain open even if your post solves Bob's immediate problem.  (@petrelharp)

**Comment by bobweek** [comment] 2022-05-07 00:12
thank you @clwgg ! however, following your approach, im now getting the error `undefined identifier p0`. after commenting out the `readFromPopulationFile` for the second species, i instead get `undefined identifier p1`. i hypothesize using `readFromPopulationFile` a second time obliterates the initialization made for the first species (which im associating with `p0` in my slim script).

**Comment by bhaller** [comment] 2022-05-07 00:28
> thank you @clwgg ! however, following your approach, im now getting the error `undefined identifier p0`. after commenting out the `readFromPopulationFile` for the second species, i instead get `undefined identifier p1`. i hypothesize using `readFromPopulationFile` a second time obliterates the initialization made for the first species (which im associating with `p0` in my slim script).

It is entirely possible that there is a bug in SLiM that prevents this from working.  I have not attempted it, and certainly before multispecies SLiM loading one tree sequence would entirely obliterate the previous simulation state.  Bob, can you post tree-seq files and a SLiM script, as minimal as possible, and well-formed in their metadata as far as you know, that reproduce the problem?  I don't understand the Python side of things, but I can certainly try to debug what is happening on the SLiM side.

**Comment by bobweek** [comment] 2022-05-07 00:46
sure thing! you'll just need to edit the paths used in the slim script.

[readFromPopulationFile.zip](https://github.com/MesserLab/SLiM/files/8644151/readFromPopulationFile.zip)

**Comment by clwgg** [comment] 2022-05-07 00:56
I'm sorry to hear that you're still getting errors @bobweek! I haven't touched the multispecies branch before, but I just threw together a (very) minimal test case and couldn't reproduce the errors you report. I still thought I'd post it here, in case it's helpful for debugging:

SLiM v4 script:
```
species all initialize() {
	defineConstant("L", 1e8);

}
species fox initialize() {
	initializeSpecies(tickModulo=3, tickPhase=5, avatar="🦊");
	initializeMutationType("m1", 0.5, "n", 0.0, 0.1);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, L-1);
	initializeRecombinationRate(1e-8);
	initializeMutationRate(0);
}
species mouse initialize() {
	initializeSpecies(tickModulo=1, tickPhase=1, avatar="🐭");
	initializeMutationType("m2", 0.5, "n", 0.0, 0.1);
	initializeGenomicElementType("g2", m2, 1.0);
	initializeGenomicElement(g2, 0, L-1);
	initializeRecombinationRate(1e-8);
	initializeMutationRate(0);
}
ticks all 1 late() {
	fox.readFromPopulationFile("species_one.trees");
	mouse.readFromPopulationFile("species_two.trees");
}
ticks all 2000 late() {
	community.simulationFinished();
}
```

[species_one.trees.zip](https://github.com/MesserLab/SLiM/files/8644160/species_one.trees.zip)
[species_two.trees.zip](https://github.com/MesserLab/SLiM/files/8644161/species_two.trees.zip)
(the files aren't actually zipped, but github doesn't let me upload `.trees` files...)
``` bash
mv species_one.trees.zip species_one.trees
mv species_two.trees.zip species_two.trees
```

The initialization trees were generated with this python script:
``` python
import msprime
import pyslim
import tskit


def build(N, suff):
    demog_model = msprime.Demography()
    demog_model.add_population(initial_size=500)
    ts = msprime.sim_ancestry(
        samples=N,
        demography=demog_model,
        sequence_length=1e8,
        recombination_rate=1e-8,
    )

    ts = pyslim.annotate_defaults(ts, model_type="WF", slim_generation=1)

    tables = ts.dump_tables()
    md = tables.metadata.copy()
    md['SLiM']['cycle'] = 1
    md['SLiM']['tick'] = 1
    tables.metadata = md
    tables.tree_sequence().dump(f"species_{suff}.trees")


def annotate(suff):
    ts = tskit.load(f"species_{suff}.trees")
    tables = ts.dump_tables()

    individual_metadata = [ind.metadata for ind in tables.individuals]
    for md in individual_metadata:
        md["subpopulation"] = 1
    ims = tables.individuals.metadata_schema
    tables.individuals.packset_metadata(
        [ims.validate_and_encode_row(md) for md in individual_metadata]
    )

    tables.populations.clear()
    md = ts.tables.populations[0].metadata
    md['slim_id'] = 1
    md['name'] = 'pop_1'
    tables.populations.add_row(md)

    tables.tree_sequence().dump(f"species_{suff}.trees")


if __name__ == "__main__":
    build(100, "one")
    build(50, "two")
    annotate("two")
```

**Comment by bobweek** [comment] 2022-05-07 01:01
wow, nice work! however, i don't think you'll get the error unless you call `p0` or `p1`. try adding

`ticks all late() {
	p0.individuals;
	p1.individuals;
}`

and see if you get any errors.

**Comment by clwgg** [comment] 2022-05-07 01:04
ah! I do indeed!
```
community.allSubpopulations[0].individuals
```
works though!

**Comment by bhaller** [comment] 2022-05-07 01:05
Well, this is weird.  OK, I'll look into it.

**Comment by bhaller** [comment] 2022-05-07 15:49
OK, I believe this is now fixed in SLiM.  There will probably be lots of little things like this that don't work properly in the context of a multispecies model; keep the issues coming.  :->

I didn't close this issue because it seems to me that there is still a Python-side issue here, that setting up a particular subpopulation id on the Python side is harder than it ought to be.  I don't know what the fix for that might be.  I am now going to attempt to transfer this issue over to pyslim; I've never done that before, we'll see how it goes.  :->

**Comment by bhaller** [comment] 2022-05-07 15:52
Hmm, GitHub won't let me transfer it to pyslim, perhaps because I don't have write access to that repo?  Well.  If you folks agree that there is an issue to be fixed on the Python side, I guess you should open a pyslim issue about that.  @petrelharp

**Closed by bhaller** 2022-05-07 15:52 UTC

**Comment by petrelharp** [comment] 2022-05-10 03:49
Thanks very much for the help, @clwgg! Very useful. Hm, let's see, though, I'm a bit muddled here. SLiM does not [have a population metadata key called `"subpopulation"`](https://github.com/tskit-dev/pyslim/blob/main/pyslim/slim_metadata.py#L330), but (unless this has changed?) gets and records its subpopulation ID from the metadata key `"slim_id"`, which [is not entirely set to 0 by `annotate_defaults`](https://github.com/tskit-dev/pyslim/blob/main/pyslim/slim_tree_sequence.py#L933) but rather to consecutive integers. So, I don't think the proposed fix above should change anything (it's just adding an unused key to the metadata).

My suspicion is that the fix to SLiM now makes your original script (with the offsetting so the two population IDs aren't the same) work, @bobweek?

I'm curious, @bhaller, what [happened here](https://github.com/MesserLab/SLiM/commit/3c1c9ad148e1f755ef5dd72f20f99091fa1c7d93#diff-8adfb8fe1a0920bc3e01ace182f148ab8d2ef19312579c78836eb89a9fbea8ceR291) under the hood?

**Comment by clwgg** [comment] 2022-05-10 05:28
@petrelharp I was referring to the **individual** metadata key called `subpopulation` which, as far as I understand, gets used [here](https://github.com/MesserLab/SLiM/blob/multispecies/core/species.cpp#L6332) to fill the `subpopInfoMap` when reading the tree sequence on `readFromPopulationFile`. Later, the **population** metadata key `slim_id` (which I also set above) gets read [here](https://github.com/MesserLab/SLiM/blob/multispecies/core/species.cpp#L6641) but, if that population ID has not been set in `subpopInfoMap` while parsing the individual table, we get NULL returned from `SubpopulationWithID` [here](https://github.com/MesserLab/SLiM/blob/multispecies/core/species.cpp#L6756), which makes us skip setting the appropriate population ID (at least in a WF model).

At least while testing this on Friday, I wasn't able to get SLiM to initialize the appropriate ID without setting **both** the individual, and the population metadata in the tree sequence, but this was just based on a quick investigation so I'd be more than happy to find out there was an easier way.

(also, as I understand the problem posed by @bobweek, `annotate_defaults` gets called on two tree sequences individually, with one population each, so they will both end up with `slim_id = 0` unless manually adjusted).

**Comment by petrelharp** [comment] 2022-05-10 06:17
Oh, sorry, you're right! I've opened an issue on pyslim.

**Comment by bobweek** [comment] 2022-05-10 15:52
> Thanks very much for the help, @clwgg! Very useful. Hm, let's see, though, I'm a bit muddled here. SLiM does not [have a population metadata key called `"subpopulation"`](https://github.com/tskit-dev/pyslim/blob/main/pyslim/slim_metadata.py#L330), but (unless this has changed?) gets and records its subpopulation ID from the metadata key `"slim_id"`, which [is not entirely set to 0 by `annotate_defaults`](https://github.com/tskit-dev/pyslim/blob/main/pyslim/slim_tree_sequence.py#L933) but rather to consecutive integers. So, I don't think the proposed fix above should change anything (it's just adding an unused key to the metadata).
> 
> My suspicion is that the fix to SLiM now makes your original script (with the offsetting so the two population IDs aren't the same) work, @bobweek?
> 
> I'm curious, @bhaller, what [happened here](https://github.com/MesserLab/SLiM/commit/3c1c9ad148e1f755ef5dd72f20f99091fa1c7d93#diff-8adfb8fe1a0920bc3e01ace182f148ab8d2ef19312579c78836eb89a9fbea8ceR291) under the hood?

after updating slim, i now get the error `no SLiM provenance table entry found`. calling `get_provenance` on a tree sequence (for either species) returns `Tree sequence is not a SLiM tree sequence (or your pyslim is out of date)`. im using pyslim version 0.700.

**Comment by clwgg** [comment] 2022-05-10 16:46
@bobweek did you add `tick` and `cycle` to the toplevel metadata? I got this error too until I added those (see also the python code in my second post above):
```
    tables = ts.dump_tables()
    md = tables.metadata.copy()
    md['SLiM']['cycle'] = 1
    md['SLiM']['tick'] = 1
    tables.metadata = md
```

**Comment by bobweek** [comment] 2022-05-10 17:48
ah ha! yes, this resolved that error. but now im back to getting `subpopulation p0 has been used already`.

**Comment by petrelharp** [comment] 2022-05-10 18:46
Hey, @bobweek - when reporting error messages, could you please also put in the code that you ran to get those messages? (maybe it's "the same code exactly as above" but there's a lot of code above...)

**Comment by bobweek** [comment] 2022-05-11 14:16
sure! attached is a compressed folder with the python script and slim script i ran to get the `subpopulation p0 has been used already` message. to get the `no SLiM provenance table entry found` message, just comment out

    ts_metadata['SLiM']['cycle'] = 1
    ts_metadata['SLiM']['tick'] = 1

for the first (host) species in the python script.

[msprime-burnin.zip](https://github.com/MesserLab/SLiM/files/8670661/msprime-burnin.zip)

**Comment by clwgg** [comment] 2022-05-11 18:09
hmm, it seems like that MWE doesn't actually include the fix I propose above, and it's commented out in the zip archive linked by @bobweek. Adding a dummy row to the population table doesn't affect how the `subpop_id` in slim is populated (at least in my limited experience over the last few days). To affect it, you'll have to set the metadata values I mention above (`slim_id` for populations, and `subpopulation` for individuals). so if I modify your MWE like this I cannot reproduce the error:

``` python
import msprime, pyslim

def add_tick_cycle(ts):
    tables = ts.dump_tables()
    ts_metadata = tables.metadata
    ts_metadata['SLiM']['cycle'] = 1
    ts_metadata['SLiM']['tick'] = 1
    tables.metadata = ts_metadata
    return tables.tree_sequence()


hts = msprime.sim_ancestry(samples=10, population_size=10, sequence_length=10)
hts = pyslim.annotate_defaults(hts, model_type="nonWF", slim_generation=1)
hts = add_tick_cycle(hts)

print("Host:")
for p in hts.populations():
    print(p)

hts.dump('hinit.trees')

pts = msprime.sim_ancestry(samples=10, population_size=10, sequence_length=20)
pts = pyslim.annotate_defaults(pts, model_type="nonWF", slim_generation=1)
pts = add_tick_cycle(pts)

ptables = pts.dump_tables()

individual_metadata = [ind.metadata for ind in ptables.individuals]
for md in individual_metadata:
    md["subpopulation"] = 1
ims = ptables.individuals.metadata_schema
ptables.individuals.packset_metadata(
    [ims.validate_and_encode_row(md) for md in individual_metadata]
)

ptables.populations.clear()
md = pts.tables.populations[0].metadata
md['slim_id'] = 1
md['name'] = 'pop_1'
ptables.populations.add_row(md)

pts = ptables.tree_sequence()

print("Parasite:")
for p in pts.populations():
    print(p)

pts.dump('pinit.trees')
```

**Comment by petrelharp** [comment] 2022-05-11 19:24
Hah, yes, sorry about that! That's what I was missing. It works now! Arguably SLiM should have thrown a different error in this situation; I'll open a separate issue. However, here's a much easier way, now that we understand the problem:
```
import msprime, pyslim

def add_tick_cycle(ts):
    tables = ts.dump_tables()
    ts_metadata = tables.metadata
    ts_metadata['SLiM']['cycle'] = 1
    ts_metadata['SLiM']['tick'] = 1
    tables.metadata = ts_metadata
    return tables.tree_sequence()

hts = msprime.sim_ancestry(samples=10, population_size=10, sequence_length=10)
hts = pyslim.annotate_defaults(hts, model_type="nonWF", slim_generation=1)
hts = add_tick_cycle(hts)

hts.dump('hinit.trees')

# here pop_0 will be an unsampled population that doesn't affect anything
demog = msprime.Demography.from_species_tree(
        "(pop_0:100000000.0,pop_1:100000000.0)A",
        initial_size={"pop_0": 10, "pop_1": 10, "A": 10}
)

pts = msprime.sim_ancestry(samples={"pop_0": 0, "pop_1": 10}, demography=demog, sequence_length=20)
# assert np.all(pts.tables.nodes.population == 1)
pts = pyslim.annotate_defaults(pts, model_type="nonWF", slim_generation=1)
pts = add_tick_cycle(pts)

pts.dump('pinit.trees')
```
