### ISSUE TITLE
update tskit

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#195] opened 2021-06-11 04:12 UTC
Next release should also update tskit - there's nothing in particular that I know of that needs the update, but something that might affect us is that tskit now allows silent mutations (ie, mutations that don't change state); and msprime can produce these (but won't with the SLiM mutation model).

**Comment by petrelharp** [comment] 2021-06-11 04:18
... oh but actually this *can* happen. This script produces a tree sequence that can't be reloaded into SLiM because it has mutations that don't result in a change of state. This won't be a problem with the updated tskit.
```
initialize() {
    setSeed(23);
    if (!exists("TREES_FILE")) defineGlobal("TREES_FILE", "out.trees");
    if (!exists("PEDIGREE_FILE")) defineGlobal("PEDIGREE_FILE", "out.pedigree");
    defineConstant("L", 1e2);
    initializeSLiMOptions(keepPedigrees=T, nucleotideBased=T);
    initializeTreeSeq();
    initializeAncestralNucleotides(randomNucleotides(L));
    initializeMutationTypeNuc("m1", 0.5, "f", 0.0);
    initializeMutationType("m2", 0.5, "n", 0.0, 0.1);
    initializeGenomicElementType("g1", m1, 1.0, mmJukesCantor(4e-2));
    initializeGenomicElement(g1, 0, L-1);
    initializeRecombinationRate(1e-2);
}

1 {
    sim.addSubpop("p1", 10);
}

1: late() {
    // add *non-nucleotide* mutations also
    sample(p1.genomes, 10).addNewDrawnMutation(m2, rdunif(10, 0, L-1));
}

10 late() {
    sim.treeSeqOutput(TREES_FILE);
    catn("Done.");
    sim.simulationFinished();
}
```

**Comment by petrelharp** [comment] 2021-06-11 04:20
Still, this is pretty niche - no hurry.

**Comment by bhaller** [comment] 2021-06-11 13:37
Can you explain what you mean by "mutations that don't result in a change in state"?  In what sense do the mutations produced by the script above not result in a change in state?  Not having a mutation, versus having a mutation, is _always_ a change in state, isn't it?  I don't understand why the script above would produce a .trees that would not reload properly.

Also, could you add an entry in the VERSIONS file stating that the tskit/kastore versions are updated with this PR?

**Comment by petrelharp** [comment] 2021-06-11 15:58
Ok, I've simplified the example. I think it just has to do with me misunderstanding how vectorization is working here - but, in my defense, I copied it out of the manual. SLiM script:
```
initialize() {
    setSeed(23);
    defineConstant("L", 2);
    initializeTreeSeq();
    initializeMutationType("m2", 0.5, "n", 0.0, 0.1);
    initializeGenomicElementType("g1", m2, 1.0);
    initializeGenomicElement(g1, 0, L-1);
    initializeMutationRate(0.0);
    initializeRecombinationRate(0.0);
}

1 {
    sim.addSubpop("p1", 2);
}

1 late() {
    sites = rdunif(2, 0, L-1);
    inds = sample(p1.genomes, 2, replace=F);
    catn("Generation " + sim.generation + " mutations to individuals " + paste(inds) + " at locations " + paste(sites));
    inds.addNewDrawnMutation(m2, sites);
}

2 early() {
    sim.treeSeqOutput('out.trees');
}
```
and python:
```
import tskit

ts = tskit.load('out.trees')

print(f"Has {ts.num_mutations} mutations at {ts.num_sites} sites.")
for m in ts.mutations():
    if m.parent != -1:
        mp = ts.mutation(m.parent)
        if m.derived_state == mp.derived_state:
            print(f"Mutation {m.id} with SLiM mutations:")
            for ds, md in zip(m.derived_state.split(","), m.metadata['mutation_list']):
                print(f"   {ds} :: {md}")
            print(f"... has parent mutation {mp.id} with SLiM mutations:")
            for ds, md in zip(mp.derived_state.split(","), mp.metadata['mutation_list']):
                print(f"   {ds} :: {md}")
```
produces:
```
$ slim test.slim && python3 test.py
// Initial random seed:
2920146924551

// RunInitializeCallbacks():
initializeTreeSeq();
initializeMutationType(2, 0.5, "n", 0, 0.1);
initializeGenomicElementType(1, m2, 1);
initializeGenomicElement(g1, 0, 1);
initializeMutationRate(0);
initializeRecombinationRate(0);

// Starting run at generation <start>:
1 

Generation 1 mutations to individuals Genome<A:0> Genome<A:0> at locations 0 0

## python:
Has 4 mutations at 1 sites.
Mutation 1 with SLiM mutations:
   1 :: {'mutation_type': 2, 'selection_coeff': -0.05740636587142944, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
   0 :: {'mutation_type': 2, 'selection_coeff': 0.245064839720726, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
... has parent mutation 0 with SLiM mutations:
   1 :: {'mutation_type': 2, 'selection_coeff': -0.05740636587142944, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
   0 :: {'mutation_type': 2, 'selection_coeff': 0.245064839720726, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
Mutation 3 with SLiM mutations:
   1 :: {'mutation_type': 2, 'selection_coeff': -0.05740636587142944, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
   0 :: {'mutation_type': 2, 'selection_coeff': 0.245064839720726, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
... has parent mutation 2 with SLiM mutations:
   1 :: {'mutation_type': 2, 'selection_coeff': -0.05740636587142944, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
   0 :: {'mutation_type': 2, 'selection_coeff': 0.245064839720726, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
```
So, I think what's happened is I've managed to insert the same mutation multiple times in the same individual. Not very likely or sensible, but possible.

**Comment by bhaller** [comment] 2021-06-11 16:54
OK, so.  First of all, the output produced for a Genome is not terribly useful here, actually; `Genome<A:0>` means that the genome is an autosome (`A`) and has 0 mutations in it (`0`), so seeing that output twice doesn't tell you whether the genomes in question are the same object or different objects.  So here's a version of the code that is a bit more informative:

```
initialize() {
    setSeed(23);
    defineConstant("L", 2);
    initializeTreeSeq();
    initializeMutationType("m2", 0.5, "n", 0.0, 0.1);
    initializeGenomicElementType("g1", m2, 1.0);
    initializeGenomicElement(g1, 0, L-1);
    initializeMutationRate(0.0);
    initializeRecombinationRate(0.0);
}
1 {
    sim.addSubpop("p1", 2);
}
1 late() {
    sites = rdunif(2, 0, L-1);
    indexes = sample(0:3, 2, replace=F);
    inds = p1.genomes[indexes];
    catn("Generation " + sim.generation + " mutations to indexes " + paste(indexes) + " at locations " + paste(sites));
    inds.addNewDrawnMutation(m2, sites);
    catn("Genomes: " + paste(p1.genomes));
}
2 early() {
    sim.treeSeqOutput('out.trees');
}
```

That produces this output:

```
Generation 1 mutations to indexes 1 3 at locations 0 0
Genomes: Genome<A:0> Genome<A:2> Genome<A:0> Genome<A:2>
```

This output tells us that `sites = rdunif(2, 0, L-1);` with this random number seed seems to be the same as `sites = c(0, 0);`.  `indexes = sample(0:3, 2, replace=F);` is the same as `indexes = c(1,3);`.  The `addNewDrawnMutation()` call is therefore requesting that two new mutations be created, both of type m2, both at location 0, in two genomes, the ones at indexes 1 and 3.  That's a *total* of two new mutations requested; one mutation will be created and added to both genomes at location 0, and then another mutation will be created and added to both genomes at location 0.  Since the stacking policy is default, that will result in the same two mutations stacked in both genomes.  And that appears to be what we have; the final output line tells us that we have two genomes that are empty, and two genomes that contain two mutations.  And the Eidos console tells us that we indeed have two mutation objects:

```
> sim.mutations
Mutation<0:0.245065> Mutation<1:-0.0574064>
```

So this all seems to make sense and be typical SLiM; just stacked mutations.  The same state could arise through normal mutation/drift, without using `addNewDrawnMutation()`.  So I'm not sure what you mean by "mutations that don't result in a change in state".

I'm not sure how to interpret the output from Python.  Do you think it is incorrect?  Can you explain what you're seeing there and what state it implies, and whether that state is the same or different from the SLiM state in the model?  Why do the parents of the mutations (0 and 2) appear to be identical to the mutations (1 and 3)?  It may be that there is a bug in the recording of state into the tree-sequence tables here.

**Comment by petrelharp** [comment] 2021-06-11 21:17
Ok, even simpler: if we add two mutations to the same location in one individual,:
```
initialize() {
    setSeed(23);
    defineConstant("L", 2);
    initializeTreeSeq();
    initializeMutationType("m2", 0.5, "n", 0.0, 0.1);
    initializeGenomicElementType("g1", m2, 1.0);
    initializeGenomicElement(g1, 0, L-1);
    initializeMutationRate(0.0);
    initializeRecombinationRate(0.0);
}

1 {
    sim.addSubpop("p1", 2);
}

1 late() {
    sites = c(0, 0);
    inds = sample(p1.genomes, 2, replace=F);
    indexes = c(1);
    inds = p1.genomes[indexes];
    catn("Generation " + sim.generation + " mutations to indexes " + paste(indexes) + " at locations " + paste(sites));
    inds.addNewDrawnMutation(m2, sites);
}

2 early() {
    sim.treeSeqOutput('out.trees');
}
```
gets
```
// Starting run at generation <start>:
1 

Generation 1 mutations to indexes 1 at locations 0 0

## python:
Has 2 mutations at 1 sites.
Mutation 1 with SLiM mutations:
   1 :: {'mutation_type': 2, 'selection_coeff': -0.05740636587142944, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
   0 :: {'mutation_type': 2, 'selection_coeff': 0.245064839720726, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
... has parent mutation 0 with SLiM mutations:
   1 :: {'mutation_type': 2, 'selection_coeff': -0.05740636587142944, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
   0 :: {'mutation_type': 2, 'selection_coeff': 0.245064839720726, 'subpopulation': 1, 'slim_time': 1, 'nucleotide': -1}
```
In other words: I'd expect to get in the tree sequence either:
- one mutation with two SLiM mutations in it, or
- two mutations, the first with only one SLiM mutation and the second with two
but instead I get
- two identical mutations, each with both SLiM mutations.
Trying to read the tree sequence back in produces an error because the second mutation results in no change of state.

If not a bug, this seems unintentional? I remember vaguely some discussion of what should happen in the case that someone tried to add lots of mutations manually in the same generation, and the result being not terribly satisfactory but stlil ok. And, in fact the current situation seems to be not wrong, just surprising.

**Comment by bhaller** [comment] 2021-06-12 03:49
Hmm.  Well, if it can't be read back in then that's a bug, for sure.  I think I see why this happens, looking at the code.  I believe that if the mutations were added one at a time, with two separate calls to addNewDrawnMutation(), the tree-seq state would then make more sense; can you confirm?  If so, one easy fix would be to simply disallow adding more than one mutation to the same position in a single call.  Force the user to add them one at a time.  Arguably that is a good policy anyway, because it isn't really clear what it's supposed to do – i.e., which order the mutations should be added.  What do you think?  Alternatively, I can fix the bug itself, by internally adding/recording/adding/recording rather than adding/adding/recording/recording.  But I think that might be a bit tricky to do in practice; not sure until I really delve into it.

**Comment by bhaller** [comment] 2021-06-12 03:55
Yeah, it would be a pain in the tuchus.  Maybe it's better to disallow use of the same position for more than one mutation.  That's a pretty weird thing to do anyway – adding stacked mutations with a single call.  Would anybody really intend to do that, and expect to be able to do it with a single call?

**Comment by bhaller** [comment] 2021-06-12 05:19
How did this arise for you?  How did you come to find this bug?  What I'm wondering is, did *you* actually intend to do this and have it work, for some actual simulation work?  Or was this discovered through a testing scenario?

**Comment by petrelharp** [comment] 2021-06-12 06:54
> I believe that if the mutations were added one at a time, with two separate calls to addNewDrawnMutation(), the tree-seq state would then make more sense; can you confirm?

Yep! Confirmed.

> How did this arise for you? 

Well, in testing the nucleotide conversion stuff I was looking at section 18.6 ("A nucleotide-based model with introduced non-nucleotide-based mutations") in trying to figure out if it was possible to have both nucleotide and non-nucleotide mutations, and saw that it was, and the way to put them in was with addNewDrawnMutation; so I thought 'gee, I'll stick a bunch of them, with
```
    sample(p1.genomes, 10).addNewDrawnMutation(m2, rdunif(10, 0, L-1));
```
So - no. Not realistic; just for testing. Totally reasonable to disallow that.

**Comment by bhaller** [comment] 2021-06-12 15:21
OK, groovy.  Next question on the same topic: you said that accepting this PR would fix this problem, in some sense.  In what sense does it fix the problem?  Just trying to fully understand what's going on here.  :->  But there seems to be no issue with accepting this PR, the duplicate-position bug we've been discussing is pretty much orthogonal as I understand it.

**Comment by bhaller** [comment] 2021-06-12 16:51
Looking into this further.  It appears that you can probably get a "mutation that doesn't change state" (I finally understand what you mean by that, I think!) by calling addMutations() requesting the addition of an existing mutation to a genome that already has a (different) mutation at the same position, if the stacking policy if "f" and thus blocks the addition.  A new derived state will be recorded, at that position for that genome, but it will be identical to the previous state.  I am inclined to ignore that issue, since (a) it sounds like the new tskit makes that a non-issue in some way (?), and (b) nobody uses policy "f" anyway, I don't think – honestly I kind of regret ever putting it in, as it just complicates things like this.

**Comment by bhaller** [comment] 2021-06-12 17:30
OK, regarding the `addNewDrawnMutation()` issue discussed above (i.e., not my immediately previous comment, which is about `addMutations()`, different issue), I realized that it was actually easy to fix the recording issue.  It used to do add-add-record-record, and it would have been hard to make it do add-record-add-record, but it was easy to make it do add-add-record, producing just one new derived state at the position rather than two duplicate derived states.  I've just done that, and your python code now emits:

```
bhaller@lanois Desktop % python3 test.py
Has 1 mutations at 1 sites.
```

It doesn't print any extra info, I guess because the mutation doesn't have a parent, which I guess is correct – the parent was the redundant derived state.  I've just committed that fix, which appears to pass unit tests.  If you could confirm that it also passes your pyslim tests, that would be great.  Once that's confirmed I'll accept this PR, I just don't want to conflate these two things together in case my bug fix is wrong.  :->

**Comment by petrelharp** [comment] 2021-06-12 20:13
> OK, groovy. Next question on the same topic: you said that accepting this PR would fix this problem, in some sense. In what sense does it fix the problem?

I meant that the duplicate mutation is "harmless" in the sense that it's a do-nothing mutation and so shouldn't affect anything. Currently, trying to load it into SLiM produces an error from tskit, but the udpated tskit allows such silent mutations, so that error won't happen any more. But, as you say, the issue is orthogonal - even if the error doesn't happen, it still doesn't seem right.

**Comment by petrelharp** [comment] 2021-06-12 20:13
> I am inclined to ignore that issue, since (a) it sounds like the new tskit makes that a non-issue in some way

Yep - sounds good.

**Comment by petrelharp** [comment] 2021-06-12 20:15
> It doesn't print any extra info, I guess because the mutation doesn't have a parent, which I guess is correct – the parent was the redundant derived state, right?

Yep - that sounds correct.  I'll check. I guess you committed this in 9e40155fc4000425ad7f914ae980e1b7b3aa147e?

**Comment by petrelharp** [comment] 2021-06-12 21:04
>  If you could confirm that it also passes your pyslim tests, and does what you expect it to do, that would be great. 

Yep - it seems to be working as expected!

**Comment by bhaller** [comment] 2021-06-12 21:05
Groovy, merged the PR.

**Closed** 2021-06-12 21:04 UTC
