### ISSUE TITLE
rescheduleScriptBlock behavior when start given but end=NULL

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#96] opened 2020-06-19 23:19 UTC
In the following recipe, the final block does not run:
```
initialize() {
    initializeSLiMModelType("nonWF");
    initializeMutationType("m1", 0.5, "g", 0.0, 2);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99);
    initializeMutationRate(0.0);
    initializeRecombinationRate(1e-8);
}

reproduction() {
	subpop.addCrossed(individual, subpop.sampleIndividuals(1));
}

1 early() {
    sim.addSubpop("p1", asInteger(40));
    sim.rescheduleScriptBlock(s99, 12);
    catn('block ' + b.id + " scheduled to run from " + b.start + " to " + b.end);
}

early() {	p1.fitnessScaling = 40 / p1.individualCount;}

s99 10 late() {
    catn(sim.generation + " done!");
    sim.simulationFinished();
}
```

This is because I'm calling `sim.rescheduleScriptBlock(s99, 12);`, which is equivalent to  `sim.rescheduleScriptBlock(s99, start=12, end=NULL);`, and apparently this does not get run at all. It does run if instead I pass `generations=12`.

I'm not sure if this a bug, strictly speaking, although looking at the script block's `start` and `end` suggests that it *should* run. It did take me a while to figure out what was happening. I suggest throwing an error if `start` is given but `end=NULL`, just as happens if `end < start`.

**Comment by bhaller** [comment] 2020-06-19 23:44
This behavior, although perhaps surprising, is intentional.  A non-null start generation with a NULL end generation is legal; if start is 12, it corresponds to a block declared as 12: for example, where the end generation is open.  As for why this behaves as it does, no rescheduling is necessary; try this model:

```
initialize() {
	initializeMutationRate(1e-7);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}
1 { sim.addSubpop("p1", 500); }
10: late() { print("foo!"); }
```

Note that "foo!" is never printed.  This is because if that block were allowed to define the final generation of the model, the model would run forever; there would be an infinite loop.  To try to ensure that that does not occur, SLiM defines the final generation for a model by the last generation spanned by a non-infinite-extent script block – generation 1, in the model above.  This is documented in section 21.7, and is probably mentioned in a few other spots in the manual.

So, not a bug, closing.  :->  But feel free to comment further if you think there would be a better way for this to work.

**Closed by bhaller** 2020-06-19 23:44 UTC

**Comment by petrelharp** [comment] 2020-06-20 00:16
Ah, I see. I figured I was probably missing something.  Putting a note about this in the help for rescheduleScriptBlock could avoid some future confusion.
