### ISSUE TITLE
Can't reload recapitated  tree to SLiM

### ISSUE THREAD

**Issue by TripleEmma** [MesserLab/SLiM#365] opened 2022-11-16 18:08 UTC
Hi,

I can't reload tree that recapitated by pyslim and mutation overlaid by msprime to SLiM.

The goal is to calculate the heterozygosity after a bottleneck event. Following suggestions by Benjamin, I first simulated the bottleneck in SLiM (step1) and then recapitated and overlaid mutation using pyslim and msprime (step2), finally reloaded the tree to SLiM to calculate heterozygosity (step3). More information could be found [here](https://groups.google.com/g/slim-discuss/c/p5LL2SB1BTY).

When running step3, I got an error:

**terminate called after throwing an instance of 'std::invalid_argument'**
**what():**
**stoll Aborted**

The version of SLiM I used is 4.0.1 and the python packages are pyslim (1.0.1), msprime(1.2.0), tskit(0.5.3). 

The scripts for each steps are as following:

**Step1**:

initialize() {
        setSeed(3591373321352);
        initializeTreeSeq(simplificationInterval=200);
        initializeMutationRate(0);
        initializeMutationType("m1", 0.5, "f", 0.0); 
        initializeGenomicElementType("g1", m1, 1);
        initializeGenomicElement(g1, 0, 529546666);
        initializeRecombinationRate(2.85533e-8);
}

1 early() {
    sim.addSubpop("p1", 2000);
    defineConstant("simID", getSeed());
}

1000 late(){
    p1.setSubpopulationSize(100);
    sim.treeSeqOutput("slim_" + simID + ".tree"); //output is slim_3591373321352.tree
}

**Step2**:

#! /usr/bin/python

import msprime, pyslim, tskit
import sys
files = sys.argv[1:]
tree = files[0]

orig_ts = tskit.load(tree)
rts = pyslim.recapitate(orig_ts, recombination_rate=2.85533e-8, ancestral_Ne=2000, random_seed=1)
ts=rts.simplify()
mutated = msprime.sim_mutations(ts, rate=1.5e-8, random_seed=1, keep=True)

names = tree.split('.')
name_tree = names[0] + '.recap.overlaid.tree'
mutated.dump(name_tree)    #final output is slim_3591373321352.recap.overlaid.tree

**Step3**:

initialize() {
    initializeTreeSeq();
    initializeMutationRate(1.5e-8);
    initializeMutationType("m1", 0.5, "f", 0.0);
    initializeGenomicElementType("g1", m1, 1);
    initializeGenomicElement(g1, 0, 529546666);
    initializeRecombinationRate(2.85533e-8);
}
1 late() {
    sim.readFromPopulationFile("slim_3591373321352.recap.overlaid.tree");
}

25 late(){
heterozygosity1 = calcHeterozygosity(p1.genomes);
cat("Mean heterozygosity = " + heterozygosity1 + "\n");
}

**Comment by bhaller** [comment] 2022-11-16 18:16
This is very helpful, thanks @TripleEmma.  Can you also attach the `slim_3591373321352.recap.overlaid.tree` file that causes the error?  (Also, it doesn't matter to this issue, but note that the standard file extension is `.trees` not `.tree`, because a tree sequence is not just one tree but many.  :->)  @petrelharp Once I've got the `.trees` file I'll look into the problem on the SLiM load end of things; but do you see any problem with the Python steps that would lead to a bad tree sequence file?

**Comment by TripleEmma** [comment] 2022-11-16 18:49
Hi @bhaller, the file size is too big. Therefore I upload [here](https://drive.google.com/file/d/10tMKhIde89P7dpN-lIwn5TU1QcesU0s7/view?usp=share_link). Thank you!

**Comment by bhaller** [comment] 2022-11-16 19:25
OK @petrelharp, it looks like `Species::DerivedStatesFromAscii()` is hitting an uncaught raise with the line:

`binary_derived_state.emplace_back((slim_mutationid_t)std::stoll(string_derived_state));`

`string_derived_state` appears to have the value `T`, which looks to be a nucleotide.  So it's not a SLiM-style derived state; it has been turned into a nucleotide by somebody.  This means, it seems to me, that this is not a legal SLiM tree sequence file at all, and an error ought to have been thrown at the start of the load process.  Looking at the Python code, it looks like mutations get overlaid with `sim_mutations()`; there needs to then be a pyslim annotation step after that to SLiM-ify the mutations, doesn't there?  Given that that step is missing, the tree sequence file should therefore not be marked as SLiM-annotated, right?  (I forget how we determine that, but I'm sure a bit of digging in the code would turn it up?)

So I see several bugs here:

- Emma's script needs to SLiM-annotate the overlaid mutations before loading back into SLiM, if I'm not mistaken; the pyslim docs have an example of that, I'm sure
- The std:stoll() function can raise, and so that raise needs to be correctly caught; right now the code is unprepared for a rise at that point; this is my problem
- The load code does not seem to be detecting that the file is not SLiM-compatible; my guess is that this is because `DerivedStatesFromAscii()` is called before `ReadTreeSequenceMetadata()` and other things, and the compatibility check is probably in that later code; this is my problem
- We ought to have a test or two in the trees test suite that tests this specific case – that a tree sequence that ought to error out as unloadable does, in fact, error out as unloadable, when generated in the various ways that that can happen; it would be great if you could tackle this part, @petrelharp.

Does this all make sense?  Or am I barking up the wrong tree somehow?

**Comment by TripleEmma** [comment] 2022-11-16 20:37
@bhaller Thank you for such quick response! 
So if I understand correctly, I should add one more command line in the recapitation step: new_ts = pyslim.annotate(mutated, model_type="WF", tick=1)? 
(I actually have no idea what the tick=1 means here. The only annotate() function example I found is : 
ts = pyslim.annotate(ts, model_type="nonWF", tick=1))

After this, I reloaded the trees into SLiM. The SLiM script is as following:

initialize() {
    initializeTreeSeq();
    initializeMutationRate(1.5e-8);
    initializeMutationType("m1", 0.5, "f", 0.0);
    initializeGenomicElementType("g1", m1, 1);
    initializeGenomicElement(g1, 0, 529546666);
    initializeRecombinationRate(2.85533e-8);
}
1 late() {
    // sim.readFromPopulationFile("slim_3591373321352.recap.overlaid.tree");
    sim.readFromPopulationFile("slim_3591373321352.recap.overlaid.annotated.trees");
}

25 late(){
heterozygosity1 = calcHeterozygosity(p1.genomes);
cat("Mean heterozygosity = " + heterozygosity1 + "\n");
}

This time it threw out a different error:
#WARNING (Species::ReadTreeSequenceMetadata): the cycle stage of the .trees file ('early') does not match the current cycle stage.
ERROR (Species::__PrepareSubpopulationsFromTables): slim_id value 1 occurred at the wrong index in the subpopulation table; entries must be at their corresponding index.

Error on script line 11, character 8:

    sim.readFromPopulationFile("slim_3591373321352.recap.overlaid.annotated.trees");
        ^^^^^^^^^^^^^^^^^^^^^^

I have tried different cycles (1, 1000, 1001) when loading the trees, but it gave the same warning. 

The slim_3591373321352.recap.overlaid.annotated.trees is [here](https://drive.google.com/file/d/1OGPGOMzqk_G8zzXFNv8HQTL7BfMsre9W/view?usp=sharing).

**Comment by bhaller** [comment] 2022-11-16 21:43
Hi Emma!  Yes, I think you need to add a call to `pyslim.annotate()` as you have now done.  You can find the doc for it here:

https://tskit.dev/pyslim/docs/latest/python_api.html#pyslim.annotate

The relevant doc for that value `tick=1` is:

> tick (int) – What tick number in SLiM corresponds to time=0 in the tree sequence.

With `tick`, I think you have a choice (and I hope I'm explaining this correctly, Peter will clarify if I'm mistaken).  The `.trees` file saved out in stage 1 has a value for this of 1000, because the file was written out in tick 1000.  So you could pass `tick=1000` to preserve that setting.  That would mean that when you reload the `.trees` file in stage 3, SLiM's tick counter would be set to 1000; and so you'd presumably want to change your `25 late()` event to be `1025 late()` instead.  In stage 3, in other words, you would load the `.trees` file in tick 1, and as a side effect of doing so, the tick counter will be set to 1000, and so if you want to go 25 more ticks and then do something, that will be tick 1025.  This is what I would recommend; keep the meaning of "time" the same throughout your pipeline, to avoid confusion.  By setting `tick=1` you are basically shifting the whole tree sequence back in time, so that what was tick 1000 in stage 1 is now tick 1 in stage 3.  Personally, I find that rather confusing; but you can do it if you wish, it should work fine (and then you would keep `25 late()` as you have it now).

I think the warning you're getting (`#WARNING (Species::ReadTreeSequenceMetadata): the cycle stage of the .trees file ('early') does not match the current cycle stage.`) is because SLiM-annotated tree sequences know the tick cycle stage (e.g., "early" or "late") when they were written out, and a warning is emitted if they are read in at a different tick cycle stage.  You are writing and reading your `.trees` files in `late()` events, so you should pass `stage="late"` to annotate, I guess?  I'm a little puzzled as to why the original setting of "late", from the `.trees` file that stage 1 wrote out, does not carry over; I would have expected that `annotate()` would only change the value if it was _told_ to change the value, but it looks like it is just overwriting the setting of "late" with "early" by default.  (Likewise for `tick`; I'm a bit surprised that it is required to supply a value at all, because I'd expect the original value of 1000 to just carry over unless a different value is supplied.)

And then there is the error you're getting (`ERROR (Species::__PrepareSubpopulationsFromTables): slim_id value 1 occurred at the wrong index in the subpopulation table; entries must be at their corresponding index.`).  I'm not sure exactly why that is happening; this is a very complex issue in the `.trees` save/load code that Peter and I have been battling for the past several versions of SLiM, and it looks like we don't yet have it quite right somehow, but this is a matter for @petrelharp, who understands this stuff better than I, I think – we need a new test case added to the trees test suite that triggers this new manifestation of the bug that we have apparently still not gotten correct in the code (aargh).  HOWEVER, even though I don't understand _why_ it's happening, I think I can probably tell you how to work around it for now: use `p0` instead of `p1`.  The issue is, fundamentally, with the fact that slot 0 in the population table is unused, because `p0` is unused in the model, which causes endless confusion between the worlds of `tskit` and SLiM.  So, just change all your `p1` usage to `p0` instead, and I think you ought to get rid of this issue.

Let us know how that goes.  Thanks!

**Comment by TripleEmma** [comment] 2022-11-16 22:41
Thank you for the suggestion and solution! @bhaller 
Yes, it works after replacing all "p1" with "p0". 

However, one more error pop up:
**ERROR (Species::__CreateMutationsFromTabulation): mutation type m0 has not been defined for this species.**

I added a line in the initialize() callback: 
initializeMutationType("m0", 0.5, "f", 0.0);

The final script is like:
initialize() {
    initializeTreeSeq();
    initializeMutationRate(1.5e-8);
    initializeMutationType("m1", 0.5, "f", 0.0);
    initializeMutationType("m0", 0.5, "f", 0.0);
    initializeGenomicElementType("g1", m1, 1);
    initializeGenomicElement(g1, 0, 529546666);
    initializeRecombinationRate(2.85533e-8);
}
1 late() { // set tick=1000 in pyslim.annotate()
    // sim.readFromPopulationFile("slim_3591373321352.recap.overlaid.tree");
    sim.readFromPopulationFile("slim_3591373321352.recap.overlaid.annotated.trees");
}

1025 late(){
heterozygosity1 = calcHeterozygosity(p0.genomes);
cat("Mean heterozygosity = " + heterozygosity1 + "\n");
}

It then ran successfully. 
But I wonder should I also specify something like initializeGenomicElementType("g1", c(m0,m1), c(1,1)) as well? Thanks!

**Comment by bhaller** [comment] 2022-11-16 22:56
Hi Emma.  Rather than defining a type `m0`, I think you need to pass the correct type to `sim_mutations()`.  I think this vignette may be quite helpful to you:

https://tskit.dev/pyslim/docs/latest/vignette_coalescent_diversity.html

There might be other lessons for you there as well, since I think it does something quite similar to what you are trying to do.  I hope that helps.

**Comment by TripleEmma** [comment] 2022-11-17 20:14
Hi @bhaller , the vignette is indeed very helpful! I now fully understand your idea (and some other concepts related to SLiM and coalescent).  Thank you!!

**Comment by bhaller** [comment] 2022-11-17 20:57
> Hi @bhaller , the vignette is indeed very helpful! I now fully understand your idea (and some other concepts related to SLiM and coalescent). Thank you!!

Great!  I'll keep this issue open since there are some action items for Peter and I from this.  Thanks!

**Comment by petrelharp** [comment] 2022-11-18 03:28
> https://tskit.dev/pyslim/docs/latest/vignette_coalescent_diversity.html

Yes - please have a look at that vignette, @TripleEmma; and in particular notice that if you put down mutations with the `SLiMMutationModel` then you don't have to do `annotate`.

**Comment by TripleEmma** [comment] 2022-11-18 19:48
Hi @petrelharp, I have done several tests. 

If specifying mut_model=msprime.SLiMMutationModel(type=1) and msprime.sim_mutations(ts, model=mut_model), I can skip the pyslim.annotate(mutated, model_type="WF", tick=1000, stage="late") while setting initializeMutationType("m1", 0.5, "f", 0.0) in SLiM. 

But I have to keep using 'p0', otherwise still getting the error:

ERROR (Species::__PrepareSubpopulationsFromTables): slim_id value 1 occurred at the wrong index in the subpopulation table; entries must be at their corresponding index.

**Comment by bhaller** [comment] 2022-11-18 19:50
> But I have to keep using 'p0', otherwise still getting the error:

Yes, that's a separate issue – and a puzzling one, since I thought we had ironed out all of those issues.  Clearly there's an edge case or two that our tree tests are not covering!  Keep using `p0` for the time being.  :->

**Comment by bhaller** [comment] 2023-07-25 14:16
Hey @petrelharp.  I'm working on this issue now.  There are several things going on, and I think some of them are in your wheelhouse.

#1 is the uncaught raise in `Species::DerivedStatesFromAscii()`, which SLiM now catches and gives an error message for:

> ERROR (Species::DerivedStatesFromAscii): a mutation derived state was not convertible into an int64_t mutation id.  The tree-sequence data may not be annotated for SLiM, or may be corrupted.

#2 is the fact that SLiM doesn't notice that the file is not correctly SLiM-annotated.  I realized that it actually has complete SLiM metadata on it, because the original tree sequence came from SLiM.  It then had mutations overlaid with msprime that were not SLiM-annotated, but the metadata is preserved across that operation, so it still looks fine.  So... is there a bug here?  Should we be able to tell, from metadata/provenance, that something fishy is going on?  I'm thinking no; we have to proceed to trying to actually read the TS data, at which point we see the bad derived state data and error out, as described above.  Do you agree?  The only alternative I can see would be to look at the provenance, and see that the provenance says that msprime has been used to modify the TS, but there is no more recent provenance entry from pyslim saying "I have re-annotated what msprime did".  But I'm not sure either msprime or pyslim is actually adding provenance entries of this sort, in a way that SLiM could check, and even if they did I'm not sure we would want to enforce such a check.

#3 is that we need a test in SLiM's trees test suite that generates a tree sequence *with* SLiM top-level metadata and provenance, but *without* correct mutation formatting, just as in Emma's code above, to see that SLiM gives a correct error message rather than barfing.

#4, I wonder – is there a problem with the way schemas are being handled by msprime or SLiM?  Specifically: the .trees file that SLiM saves specifies SLiM's mutation metadata schema.  When msprime overlays mutations, the mutations it overlays do not conform to that schema, I suppose; they conform to whatever msprime's schema is.  I guess msprime should actually change the schema, in the tree sequence it saves out, to reflect that, right?  And then SLiM ought to check the schema on read, see that it is not SLiM's own schema, and error out with "Not SLiM-annotated" or something?  I don't know whether msprime is changing the schema or not.  SLiM does not appear to check the schema for correctness on read.  Is there a bug here, anywhere?

#5, there seems to again be a problem with the population table and the empty row and p0 versus p1.  I am hopeful that this problem that Emma saw has since been fixed by us; I remember we had to revisit that issue again a while back, but I'm not sure of the chronology.  It would be great if you could check on that, looking at what Emma did above that caused the error.

So, I've fixed #1 just now.  #2 and #4 are maybe not a problem, I'm just checking with you on them.  #3 and #5 are action items for you.  I'm hoping to roll SLiM 4.1 pretty soon, so handling these open issues is now fairly high priority.  :->  (And by the way, is there a way to use the '#' symbol to refer to numbered items without GitHub thinking you're talking about issue numbers?)

**Comment by petrelharp** [comment] 2023-07-25 15:06
2) 

> Should we be able to tell, from metadata/provenance, that something fishy is going on? I'm thinking no; we have to proceed to trying to actually read the TS data, at which point we see the bad derived state data and error out, as described above. Do you agree?

Yes, I agree. (We cannot rely on provenance, in particular.)

3-5) Sounds good. I can do that soon.

about `#` - seems like not?

**Closed** 2023-09-14 13:23 UTC
Labels: bug, priority
