### ISSUE TITLE
Compiling with older version of g++

### ISSUE THREAD

**Issue by samyeaman** [MesserLab/SLiM#191] opened 2021-06-06 19:26 UTC
I was attempting to compile from source code on a server running CentOS 6.4 with g++ 4.4.7 as the standard compiler, but with a module loaded from gcc/4.8.2rev203690 so that a call to gcc --version returns gcc (GCC) 4.8.2. So it looks like the machine is running a compiler that should work with SLiM3, but the standard makefile approach didn't work, and the make command: 

cmake ../SLiM
make slim 

threw this error:

cc1: error: unrecognized command line option "-std=c11"

Seems perhaps like an issue with the makefile?

**Comment by bhaller** [comment] 2021-06-06 19:43
Yep, ok.  As I understand from email, it looks like cmake is not finding the right gcc even though `gcc --version` returns 4.8.2 after you have loaded that module, so my guess it is an issue with (a) SLiM's cmake config file, (b) cmake being dumb, or (c) the module-loading thing not setting up the environment config that cmake expects.  My seat-of-the-pants guess is (c); it might be instructive to try to build a minimal "hello, world" cmake-based project and see whether than project finds and builds with 4.8.2, or if it, too, still uses 4.4.7.  If it also still uses 4.4.7, then the problem is clearly (b) or (c).  If it uses 4.8.2, then the finger points towards (a), but I have no idea what the issue might be.

Oh, it occurs to me that one thing you might check, right out of the gate, is what version of cmake is provided on your cluster.  If the gcc is ancient, maybe the cmake is too, and so maybe the ancient cmake doesn't understand where to find the right compiler.  If there's a module for an updated cmake as well, try loading that.

**Comment by bhaller** [comment] 2021-06-23 02:35
Since this build issue seems to be specific to one particular cluster's toolchain setup, and involves a compiler version that is unsupported, I'm going to close it for now.  @samyeaman, if it turns out that there's a SLiM bug here to be addressed, please comment and I'll reopen the issue.  :->

**Closed by bhaller** 2021-06-23 02:35 UTC
Labels: help wanted
