### ISSUE TITLE
emojis not appearing in slimgui on ubuntu

### ISSUE THREAD

**Issue by bobweek** [MesserLab/SLiM#306] opened 2022-04-18 17:33 UTC
installing slim 4.0 (multispp branch) and building slimgui (with qt 5.15.2) on ubuntu 21.10, some emojis used as species avatars appear as empty rectangles. this does seem to be an issue with ubuntu as these emojis can be pasted into a terminal just fine. see screenshots below.

![Screenshot from 2022-04-18 13-26-01](https://user-images.githubusercontent.com/7787773/163848201-af9a0a54-c8d8-4b16-aa3c-85797a33be91.png)
![Screenshot from 2022-04-18 13-16-03](https://user-images.githubusercontent.com/7787773/163848204-533bcca6-40b1-4419-9306-371b0274b111.png)

**Comment by bhaller** [comment] 2022-04-18 17:39
Surprising that the mouse renders but the fox does not.  Also surprising that the mouse renders with a different image than it does in your terminal.  And also surprising that both the fox and the mouse show in the editor with an extra space character after them, as if Qt doesn't understand the font spacing for emojis.  Overall, a disappointing showing by Ubuntu here.  Note that if all this bothers you, it should work to instead give them avatars that are not emojis, like `"F"` and `"M"` or `"(F)"` and `"(M)"` or whatever.  If you develop any further insight into what might be going on, please post an update.

**Comment by grahamgower** [comment] 2022-04-19 07:08
Emojis show up just fine for me on Arch Linux, so I suspect that you may have a local font configuration/installation problem. What font are you using in your terminal? Maybe you could try using that same font in the SLiM GUI? Do you have the [noto](https://fonts.google.com/noto) font package(s) installed (I don't know the ubuntu package names, sorry)? Maybe try rebuilding your font cache (`fc-cache -f`, or similar)?

The rendering differences between the terminal and the SLiM GUI might be a Qt bug.
https://bugreports.qt.io/browse/QTBUG-85744

Apparently there are two types of fonts, bitmap fonts and vector fonts. On your terminal, you're seeing the former (full colour), whereas in your SLiM screenshot the fox is using a vector font (two colour outline). I also see outlines in SLiM, regardless of the font I choose. However, I see bitmap fonts in some other applications when selecting the "same" font (I mostly use "DejaVu Sans Mono").

**Comment by bobweek** [comment] 2022-04-19 14:04
okay, first i set slimgui to the same font as my terminal (source code pro), but no luck. so then i installed the noto font package and still no luck (even after reboot). i rebuilt my font cache using the provided command above, still no luck. i also went through to each font option available in slimgui, same results for each.

**Comment by grahamgower** [comment] 2022-04-19 14:29
Well there seems to be a *ton* of Qt bugs relating to fonts and emojis.
Maybe we have too many fonts installed (!): https://bugreports.qt.io/browse/QTBUG-80434

Interestingly, I copied the `75-noto-color-emoji.conf` file from https://gist.github.com/charveey/091b11ea554436d15c7fffcf01129a8a into `/etc/fonts/conf.d/`, then after running `fc-cache -f` and restarting SLiM GUI I see the full colour fox and mouse. I won't pretend to understand how `fontconfig` works or why this helps.

**Comment by bobweek** [comment] 2022-04-19 14:39
that worked for me too! interestingly, the mouse tab avatar still appears as an outline.
![Screenshot from 2022-04-19 10-37-50](https://user-images.githubusercontent.com/7787773/164029673-253c8ceb-88ed-4176-8a59-2f6bd4e3fd35.png)

**Comment by bhaller** [comment] 2022-04-19 14:46
OK, this sounds complicated, and I think I'll treat it as a doc bug: I'll document what @grahamgower found as the recommended fix.  Thanks!

**Comment by bhaller** [comment] 2022-05-07 18:05
OK, this is fixed in the SLiM 4 doc; closing.  For posterity, I wrote this (some of which was already there):

SLiMgui uses emojis in a couple of places.  For example, it shows the “snake” emoji, 🐍, after Python recipes in the Open Recipe menu.  Also, multispecies models typically set up emojis as “avatars” for the species being simulated, which SLiMgui uses to represent the species in its user interface.  If you notice “missing symbol” boxes where emojis ought to be, or if they don't display at all, you may need to install an emoji font that provides the “snake” emoji.  In the Arch distro, at least, the relevant package is named noto-fonts-emoji.  Ubuntu 18.04 LTS and 20.04 LTS seem to come with the necessary font preinstalled, but you could check that they are correctly installed on your system (see https://fonts.google.com/noto).

If you still have problems with emoji display in SLiMgui, Graham Gower recommends surfing to https://gist.github.com/charveey/091b11ea554436d15c7fffcf01129a8a and copying the file there named 75-noto-color-emoji.conf into /etc/fonts/conf.d/.  Then run fc-cache -f, and then restart SLiMgui.  Presumably more recent versions of Linux distros will fix these issues out of the box; but note that since new emojis are being added all the time, some emojis may display correctly while others do not.  Furthermore, some emojis may display in SLiMgui in full color, while others display only as an outline.  Numerous bugs in Qt seems to be entangled with all of this; there is not much SLiMgui can really do about it; the problem is really manifesting at lower software levels.  For further discussion, see https://github.com/MesserLab/SLiM/issues/306.

**Closed by bhaller** 2022-05-07 18:05 UTC
Labels: bug, qtslim
