### ISSUE TITLE
dictionaries in top-level tree sequence metadata have lists wrapped around them in output

### ISSUE THREAD

**Issue by petrelharp** [MesserLab/SLiM#236] opened 2021-10-30 06:19 UTC
For some reason, nested dictionaries in metadata output have `[ ]` wrapped around them, so they are loaded as lists of length one, containing a dictionary. Here's a MWE:
```
initialize() {
	initializeTreeSeq();
	initializeMutationRate(1e-7);
	initializeMutationType("m1", 0.5, "f", 0.0);
	initializeGenomicElementType("g1", m1, 1.0);
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}
1 {
	sim.addSubpop("p1", 5);
}
2 late() {
	sim.treeSeqOutput(path="test.trees", metadata=Dictionary("a", Dictionary("b", c(1, 2, 3))));
}
````
and here's the metadata, first showing how it's parsed by default; then showing the raw string version that SLiM puts there:
```
>>> import tskit
>>> ts = tskit.load("test.trees")
>>> ts.metadata
{'SLiM': {'file_version': '0.6', 'generation': 2, 'model_type': 'WF', 'nucleotide_based': False, 'separate_sexes': False, 'spatial_dimensionality': '', 'spatial_periodicity': '', 'stage': 'late', 'user_metadata': {'a': [{'b': [1, 2, 3]}]}}}
>>> t = tskit.load("test.trees").tables
>>> t.metadata_schema = tskit.MetadataSchema(None)
>>> t.metadata
b'{"SLiM":{"file_version":"0.6","generation":2,"model_type":"WF","nucleotide_based":false,"separate_sexes":false,"spatial_dimensionality":"","spatial_periodicity":"","stage":"late","user_metadata":{"a":[{"b":[1,2,3]}]}}}'
```
In particular, extracting the thing I put in doesn't work as expected:
```
>>> ts.metadata["SLiM"]["user_metadata"]["a"]["b"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers or slices, not str
>>> ts.metadata["SLiM"]["user_metadata"]["a"][0]["b"]
[1, 2, 3]
```

**Comment by bhaller** [comment] 2021-10-30 13:19
This is intentional and expected.  As the doc says:

`For example, a Dictionary with a key "key1" with integer value 1:3 and key "key2" with string value "value2" would produce the JSON serialization '{"key1":[1,2,3],"key2":["value2"]}', where the outer single quotes are not part of the serialization itself, but are indicating that the serialization is a string value.  Note that since all Eidos values are vectors, even singleton values are serialized into JSON as arrays by Eidos; the hope is that this will make automated parsing of these JSON strings easier, since the singleton case will not have to be special-cased.`

Everything is a vector in Eidos, so that "nested dictionary" was, in fact, a vector of length 1 containing a Dictionary as its single element, and so it was serialized as such.  If this presents a real problem it could be changed, with special-case code to treat the singleton case as if the vector did not exist; but that would be inconsistent with what the language actually expresses, I think, and would (as the doc notes) make parsing serializations have to special-case the singleton case on the other end, too, rather than being able to reliably assume that values from Eidos are always vectors.

So, closing this as "intentional behavior", but if you strongly disagree it can be reopened.  Note that changing this now would require breaking backward compatibility, though.  This has been part of the Dictionary spec since it was first implemented.

**Closed by bhaller** 2021-10-30 13:19 UTC

**Comment by petrelharp** [comment] 2021-10-31 03:57
Ah, sorry - I did read that but I guess I read "singleton values" to mean like single numbers.

Ah, I see:
```
> length(c(c(c(1,2,3,4))))
4
> b = Dictionary('x', Dictionary('b', 1))
> b[0]
{x={b=1;};}
> b
{x={b=1;};}
> b[0][0][0][0]
{x={b=1;};}
```
🤯 

I guess what bothers me is that you can't round-trip JSON without putting lists around everything first. But I guess that's just how Eidos works! The "everything is a vector" *is* a very nice thing about Eidos, btw.

I do think an explicit example would be helpful, like:
```
For instance, `Dictionary("a", 1, "b", Dictionary("x", 2))` would be serialized as `{"a" : [1], "b" : [{ "x" : [2] }]}`.
```

**Comment by bhaller** [comment] 2021-11-02 14:36
OK, I have added that to the doc, thanks for the suggestion.

If the problem here was just the unexpected behavior, then we're done.  If this actually causes significant inconvenience/problems in usage, then I could add a new optional flag to serialize, like `[simplifySingletons=F]`, that would do that; but really that might just muddy the waters, IMHO.  Everything is a vector.  :->
