### ISSUE TITLE
add `quantile` to Eidos

### ISSUE THREAD

**Issue by mufernando** [MesserLab/SLiM#100] opened 2020-07-22 14:27 UTC
In #74 I inquired about adding a `quantile` function to Eidos. I bet this would have many uses, but most importantly it is essential for simulating truncation selection in SLiM.

@bhaller rightfully raised the issue that `R`s implementation of `quantile` includes many different methods, which differ in how they handle interpolation. I think we don't need anything fancy, so I propose we implement a mid-point interpolation. That is, when  a quantile lies between two data points `i<j`, we return `(i+j)/2`. This is really equivalent to [`numpy`s midpoint interpolation](https://numpy.org/devdocs/reference/generated/numpy.quantile.html).

To get started, I wrote a Eidos `quantile` function that does exactly what I said above:

```
function (numeric)quantile(numeric x, float q) {
    pos = q*(length(x)-1);
    //midpoint impl
    idx = order(x);
    x_below = x[idx[floor(pos)]];
    x_above = x[idx[ceil(pos)]];
    return (x_below+x_above)/2;
}
```

@bhaller how does this sound? I can get some example arrays, quantiles and expected results for you to use as a test. It would be great if you could implement it, as I'm kind of swamped right now. But I don't think this is urgent.

**Comment by mufernando** [comment] 2020-07-22 14:57
ah, see here for some how numpy tests things:

https://github.com/numpy/numpy/blob/a39e3021b9304fb5a76542d444b7fec2dcff1374/numpy/lib/tests/test_function_base.py#L2697-L2703

**Comment by bhaller** [comment] 2020-07-22 15:25
Great, thanks for the Eidos implementation and the test, this is now very clear.  @petrelharp, does this seem to you to be the correct approach to take?  I ask since this is a math-y thing.  ;->  Note that I can always add a `type` optional argument to the function later on, preserving backward compatibility, if other types of quantile calculation are needed.

**Comment by petrelharp** [comment] 2020-07-22 17:25
Hm, good question. My strong prior is that we should do it however R does it, and probably the default method. However, `?quantile` says that R's choice is inherited from S, and maybe just locked in by history. 

Here's a comparison of the 9 methods:
```
n <- 6
x <- runif(n)
y <- rexp(n)
p <- seq(0, 1, length.out=101)
qx <- sapply(1:9, function (k) quantile(x, probs=p, type=k))
qy <- sapply(1:9, function (k) quantile(y, probs=p, type=k))

layout(1:2)
matplot(p, qx, type='l', lty=1, col=1:9)
points((1:n)/(n+1), sort(x))
matplot(p, qy, type='l', lty=1, col=1:9)
points((1:n)/(n+1), sort(y))
legend("bottomright", lty=1, col=1:9, legend=1:9)
```
![Screenshot from 2020-07-22 10-12-33](https://user-images.githubusercontent.com/1046249/88206904-e0ff0900-cc03-11ea-8cde-74a704972ae1.png)

I think we should *definately* do one of R's methods - is this "midpoint" one of those? (I don't think so?)  I'd vote for one of the continuous methods, it type 4-9. Of these, type 4 is easiest to explain (and maybe closest to what you had in mind, @mufernando?), type 7 is default, and type 8 has maybe the best theoretical properties. I think they all look easy to implement, so I'd go for either 7 or 8.

Here's [R's source code](https://github.com/wch/r-source/blob/5d2801f199cd14be3b1c2d06994cf25de8426cc1/src/library/stats/R/quantile.R), which looks translatable.

Also, I vote for only implmementing one type of quantile. No need to overcomplicate things - Eidos is not trying to be a statistical language.

*Oh:* but, @mufernando - for the use case you propose, what properties do you need? e.g. if all values are unique, if q = quantile(x, p), do you always need that `sum(x <= q) == floor(length(x) * p)`? (all the above methods might do that, not sure)

**Comment by mufernando** [comment] 2020-07-22 18:10
I'm not sure my proposed implementation is one of R's methods, but I feel like it should be in there. This is the method introductory statistics courses usually teach, AFAIK. The notation in R docs is so obscure to me that I can't tell, but maybe it is type 5?

I think truncation selection would be better defined if `sum(x <= q) == floor(length(x) * p)`. Because then we would be selecting a consistent number of individuals every generation.

**Comment by petrelharp** [comment] 2020-07-22 19:59
Your implementation isn't continuous, right? So it's not type 5?

> I think truncation selection would be better defined if sum(x <= q) == floor(length(x) * p). Because then we would be selecting a consistent number of individuals every generation.

This will never be true if the values of x aren't unique - if you want to do that, a better way is to use `order <= floor(length(x) * p)` for truncation selection. So maybe that point is moot.

**Comment by bhaller** [comment] 2020-07-22 20:08
Interesting.  Well, I'm happy to implement whichever you settle on, as long as we can figure out how.  The R code is pretty opaque to me, since I don't really understand the mathematical ideas involved.

**Comment by mufernando** [comment] 2020-07-22 22:22
> This will never be true if the values of x aren't unique - if you want to do that, a better way is to use `order <= floor(length(x) * p)` for truncation selection. So maybe that point is moot.

I think by definition all quantile stats should have this property, @petrelharp. In essence your snippet is one of the quantile implementations from R (one of the discontinuous). I still think there is value in implementing `quantile` in Eidos so a broader audience can perform truncation selection easily.

I found [this repo](https://github.com/eurostat/quantile/tree/master/src) where all types of quantiles were reimplemented in a bunch of language that may help in the implementation, @bhaller. I agree with @petrelharp that type 8 is better for most applications.

**Comment by bhaller** [comment] 2020-07-22 23:11
If you wanted to contribute a truncation selection example, that would be great.  Note that there is already an example of truncation selection using a threshold QTL-based phenotypic value (section 13.6), but I take it you want to do something slightly different?  Killing off the bottom 10% of phenotypic values, or some such?

Well, so, are we agreed on adding R's type 8 quantile function?  @petrelharp, do you think it's OK to change the behavior relative to R's default quantile function (so long as that is documented)?  @mufernando, that repo you found looks useful; do you know which of the algorithms they implement corresponds to R's type 8?

**Comment by mufernando** [comment] 2020-07-22 23:15
type 8 in there should be R's type 8.

**Comment by petrelharp** [comment] 2020-07-23 05:10
Whoops - the code for truncation selection is not `order <= floor(length(x) * p)`, it's `rank <= floor(length(x) * p)`, but we don't have `rank` (I always mix those up), so:
```
fitness = rep(0, length(x));
fitness[order(x)[seqLen(asInteger(length(x) * p)))]] = 1;
```

**Comment by bhaller** [comment] 2020-07-23 05:17
> Whoops - the code for truncation selection is not `order <= floor(length(x) * p)`, it's `rank <= floor(length(x) * p)`, but we don't have `rank` (I always mix those up), so:
> 
> ```
> fitness = rep(0, length(x));
> fitness[order(x)[seqLen(asInteger(length(x) * p)))]] = 1;
> ```

Where `x` is what, exactly?  What are you ordering by?

**Comment by petrelharp** [comment] 2020-07-23 05:23
Also, btw: this is not true for any of these methods, all the time, so that's a red herring: `sum(x <= q) == floor(length(x) * p)`.

And, sorry - if `x` is a numeric vector of length `n` and we want to construct a vector `f` that has 1 in the slots corresponding to the smallest `k` entries of `x` and 0 otherwise, we'd do:
```
f = rep(0, n);
f[order(x)[seqLen(k)]] = 1;
```

**Comment by petrelharp** [comment] 2020-07-23 05:28
But, that's a tangent! As for the quantile function, I guess I vote for keeping it at the R default. That'll be easier to explain and test, and is a fine choice. For instance, it has the pleasing property that
```
> quantile(0:100, probs=0.95, type=7)
95% 
 95 
```
which is not shared by any of the other continuous methods:
```
> sapply(1:9, function (k) quantile(0:100, probs=0.95, type=k))
    95%     95%     95%     95%     95%     95%     95%     95%     95% 
95.0000 95.0000 95.0000 94.9500 95.4500 95.9000 95.0000 95.6000 95.5625 
```

I'm happy to help implement this, but not right now.

**Comment by bhaller** [comment] 2020-07-23 05:39
> And, sorry - if `x` is a numeric vector of length `n` and we want to construct a vector `f` that has 1 in the slots corresponding to the smallest `k` entries of `x` and 0 otherwise, we'd do:
> 
> ```
> f = rep(0, n);
> f[order(x)[seqLen(k)]] = 1;
> ```

Yeah, I'm just wondering what `x` *is*, in your model.  A phenotypic trait value?  Based on QTLs or something else?  Or fitness?  Or...?  :->

**Comment by bhaller** [comment] 2020-07-23 05:41
> But, that's a tangent! As for the quantile function, I guess I vote for keeping it at the R default.

OK, makes sense to me.  Does that work for you @mufernando ?

> I'm happy to help implement this, but not right now.

OK, thanks.  I can probably get there, based on the links you guys have given me.  :->

**Comment by petrelharp** [comment] 2020-07-23 05:47
Oh, sorry - `x` is a quantitative trait (phenotype), from `sumOfMutationsOfType( )`.

**Comment by mufernando** [comment] 2020-07-23 15:38
Yes, it makes sense! @bhaller after you implement the quantile type 7, I can contribute some more to the section of the manual with truncation selection. 

The thing we currently have there is not "typical" truncation selection, but I'm not sure what to call it. Truncation selection is when only individuals whose phenotype are at the top (or bottom) x% of the trait distribution contribute to the next generation. So the threshold is defined based on the rank of individual's phenotype, not on the raw value.

**Comment by mufernando** [comment] 2020-07-23 15:40
ok, I changed my mind. Truncation selection can refer to selection on phenotype percentile or raw phenotypic value. See [here](http://nitro.biosci.arizona.edu/zbook/NewVolume_2/pdf/WLChapter14.pdf).

**Comment by bhaller** [comment] 2020-07-25 00:39
OK, so, something is wrong and I can't figure out what.  I'm working from the Eurostat C implementation that @mufernando linked to, which is here:

https://github.com/eurostat/quantile/blob/master/src/quantile_source.c

Their type 7 does appear to be R's type 7, as far as I can tell, so that is what I have been working with.  The problem I am running into is that the indices calculated are all one too high, except at the very end of the `x` vector, so:

`quantile(0:100);`

which should produce `(0 25 50 75 100)` in fact produces `(1 26 51 76 100)`, and:

`quantile(c(17, 12, 4, 87, 3, 1081, 273));`

which should produce `(3 8 17 180 1081)` in fact produces `(4 14.5 87 677 1081)`.

So the values produced are wrong, but it is the calculated indices into `x` that are at fault.  For example, in the second example above, the median should be 17 (the middle `x` value when `x` is sorted), but it is 87 (the next higher `x` value when `x` is sorted).

Looking at the Eurostat C code, this appears to be the behavior that it codes for, in fact.  Consider the case when a probability `p==0.0` is requested; this should return the 0th sorted value, for type 7.  The code calculates `m = 1-p` (for type 7), so `m` is 1.0 (from the `M_INDICE` macro).  Then it calculates `j = math.floor(N*p + m)` with the `J_INDICE` macro; so `j = math.floor(N*0.0 + 1.0)`, or `1.0`.  But `j` is the index of the first observation to be included in the weighted average that produces the quantile value; for `p==0.0`, it should be 0, not 1.  So visual inspection of the code suggests that it will produce the wrong answer.  I haven't tried to build it yet.

My first thought was that their code was somehow written for 1-based indices, like R (even though C is a 0-based language, like Eidos).  But the code explicitly checks for `j==0` and sets `firstobs = obs = 0`, and checks for `j==N` and sets `firstobs = obs = N-1`, so it is clearly designed to work with indices in [0,N-1], not in [1,N].  As far as I can tell, for type 7 `j` will never equal zero, though, and so `firstobs` will always be >= 1.  Which is wrong.

So.  Probably I'm wrong, not them – assuming they tested their code, like, at all – but I can't figure out why.  Here is the core part of my code:

		for (int probs_index = 0; probs_index < probs_count; ++probs_index)
		{
			double prob = probs[probs_index];
			double m = 1.0 - prob;				// R type 7
			long j = (long)std::floor(x_count * prob + m);
			double g = x_count * prob + m - j;
			
			long firstobs, obs;
			if (j == 0) firstobs = obs = 0;
			else if (j == x_count) firstobs = obs = x_count - 1;
			else {
				firstobs = j;
				obs = j + 1;
			}
			
			double quantile = (1.0 - g) * x_value->FloatAtIndex((int)order[firstobs], nullptr) +
									  g * x_value->FloatAtIndex((int)order[obs], nullptr);
			
			float_result->set_float_no_check(quantile, probs_index);
		}

Any ideas?  The R code does things a little differently and I don't understand it, so I can't really work from it.  It feels to me like the expression for `j`, `floor(x_count * prob + m)`, is just incorrect for 0-based indices, since for `prob==0.0` it produces 1 and it needs to produce 0.  What am I missing??

**Comment by bhaller** [comment] 2020-07-25 01:48
Well, I've been fighting for a while to get the Eurostat C code to build.  I think I'm almost there, but... the code in GitHub is bizarrely wrong and is not even close to compiling, as far as I can tell.  All kinds of small weird things are wrong with it that would (and did) produce compile errors.  And there is no Makefile supplied, so you have to figure that out yourself.  And so forth.  Very weird for a public repository based on a published paper.  But anyway, who cares about their code, in the end.  The question, ultimately, is: why does my code not work?

**Comment by bhaller** [comment] 2020-07-25 01:52
Finally got it to build, and it does indeed exhibit the same bug (doing quartiles of 0:10 here):

0.000000: 1.000000
0.250000: 3.500000
0.500000: 6.000000
0.750000: 8.500000
1.000000: 10.000000

So the question is why?

**Comment by mufernando** [comment] 2020-07-26 19:12
This is really weird, @bhaller. Given this was published and all the code was available I thought it was reliable... Can you share the full code?

**Comment by bhaller** [comment] 2020-07-26 19:20
Full code for theirs or for mine or both?

**Comment by petrelharp** [comment] 2020-07-26 20:04
I can have a look in a couple of days. My first step will be to compare to r on a bunch of random examples.

**Comment by mufernando** [comment] 2020-07-26 20:24
your implementation!

**Comment by bhaller** [comment] 2020-07-26 20:43
> your implementation!

Sorry, I thought you might want my corrected version of their code, since it took me a little while to get it to build.  :->

OK, simplest thing is to just commit it as it is right now.  I've just done so; it's in the GitHub master branch now.  There's a self-test defined for it, so if you do -testEidos you will get an error because quantile() is not doing what it is supposed to.  The code itself is in eidos_functions.cpp, in Eidos_ExecuteFunction_quantile().

**Comment by bhaller** [comment] 2020-07-26 21:53
@mufernando I just did another commit; now quantile() ought to be the only thing that will generate a failure with -testEidos, I think.  Sorry; I'm in the middle of overhauling a bunch of low-level stuff...

**Comment by bhaller** [comment] 2020-07-31 13:24
@mufernando any news on this front?

**Comment by petrelharp** [comment] 2020-07-31 22:52
I'm having a look at the implementation now... it'd be easier to look at if it was separated out in a PR, though, FYI.

**Comment by petrelharp** [comment] 2020-07-31 23:07
Instead of checking the C++ code, I wrote an easier-to-understand version of the R source code (and tested it):
```
myq <- function (x, probs) {
    n <- length(x)
    x <- sort(x)
    out <- rep(NA, length(probs))
    for (j in seq_along(probs)) {
        p <- probs[j]
        index <- 1 + (n - 1) * p
        lo <- floor(index)
        hi <- ceiling(index)
        out[j] <- x[lo]
        if (index > lo && x[hi] != out[j]) {
            h <- (index - lo)
            out[j] <- (1 - h) * out[j] + h * x[hi]
        }
    }
    return(out)
}

for (x in list(1:10, runif(11), rep(0, 11), rnorm(201))) {
    for (probs in list(0.5, seq(0, 1, 5), seq(0, 1, 100), runif(5), 0.0, 1.0, 0.9999)) {
        a <- quantile(x, probs)
        b <- myq(x, probs)
        stopifnot(all.equal(a, b, check.attributes=FALSE))
    }
}
```

It doesn't deal with missing values, etcetera, but perhaps this helps?

**Comment by bhaller** [comment] 2020-07-31 23:20
> Instead of checking the C++ code, I wrote an easier-to-understand version of the R source code (and tested it):
> ...
> It doesn't deal with missing values, etcetera, but perhaps this helps?

I haven't looked at your code yet, beyond a glance, but: R is 1-based whereas C is zero-based, and I think that may be where the issue is arising.  So R code that works perfectly, if translated directly to C, will produce off-by-one errors – as their code, and now my code, appears to do.  So I guess the question is: what's the correct way to fix those off-by-one errors?

**Comment by bhaller** [comment] 2020-07-31 23:23
> I'm having a look at the implementation now... it'd be easier to look at if it was separated out in a PR, though, FYI.

Sorry.  The diffs were already on my machine; when I'm working by myself, I don't normally make branches or PRs for my work unless it's something very large.  I don't know how to turn existing changes that I already have on my machine into a PR.  (Indeed, I'm not sure I know how to create a PR at all, although I have more or less learned how to merge them by pressing the big green "merge" button.  :->)

**Comment by petrelharp** [comment] 2020-08-01 00:14
>  I don't know how to turn existing changes that I already have on my machine into a PR.

The short answer is "make a new branch, and push it to github"; then if you go to github it'll give you the option to make a new PR (or just click on the "new PR" button somewhere).  If you already have changes commited to your computer's master, then you do `git checkout -b new_stuff` and voila you have a new branch.

**Comment by petrelharp** [comment] 2020-08-01 00:17
To be zero-indexed, we'd just need to change the line to
```
        index <- (n - 1) * p
```
(I edited the code above to say so.)

**Comment by bhaller** [comment] 2020-08-01 00:21
> To be zero-indexed, we'd just need to change the line to
> 
> ```
>         index <- (n - 1) * p
> ```
> 
> (I edited the code above to say so.)

Hmm.  Well, I tried pretty much that change in the C code, and it didn't work.  I can try to compare your R code to my C code tomorrow and see if I can figure it out.  It's difficult since I don't actually understand what the algorithm is doing very well.

**Comment by petrelharp** [comment] 2020-08-01 00:24
I've edited my code  (above) and used a dirty trick to make my implementation code zero-indexed, and it still seems to work - so, that should do it.

**Comment by bhaller** [comment] 2020-08-01 01:08
OK, thanks, probably this will get me over the hump.  :->

**Comment by petrelharp** [comment] 2020-08-01 01:33
I think I've got this fixed over in #105, although maybe there's C++ things I didn't do right...

**Comment by bhaller** [comment] 2020-08-01 01:35
Awesome!  I'll check it out!

**Comment by bhaller** [comment] 2020-08-01 02:33
Yes, #105 fixed it.  I'll mark this issue as fixed once I've committed the changes.  Thanks!

**Comment by bhaller** [comment] 2020-08-02 00:42
This has been committed to the master branch, should be all working now.  Let me know if you see any problems.  Enjoy!  (Oh, and @petrelharp , if you want to send me an addition to the documentation to more explicitly describe the algorithm used, that would be nice; right now I just say something like "this uses R's default 'type 7' algorithm".)

**Closed by bhaller** 2020-08-02 00:42 UTC
Labels: enhancement

**Comment by petrelharp** [comment] 2020-08-02 04:33
Oh, right: um, let's see: how's this?

"
The quantile function linearly interpolates between the points of the empirical cumulative distribution function.
in other words, if x is a vector of length n+1, then the quantiles with probs=(0, 1/n, 2/n, ..., (n-1)/n, 1) are equal
to the sorted values of x, and the quantile is a linear function of probs otherwise.
(Note: this corresponds to R's default quantile method.)
"

**Comment by bhaller** [comment] 2020-08-02 14:42
Thanks, done.  And so much clearer than R's doc; now I understand what the algorithm does!  :->

**Comment by mufernando** [comment] 2020-08-02 14:43
Thanks for pushing this forward @bhaller and @petrelharp! Sorry I couldn't be of more help, but this past week has been crazy busy.
