### ISSUE TITLE
SLiM gui forces dedicated gpu

### ISSUE THREAD

**Issue by eyalbenda** [MesserLab/SLiM#95] opened 2020-05-16 23:51 UTC
Thank you for this fantastic software!
I noticed that running the SLiM guy forces my MacBook to use the dedicated GPU. Is there a reason this is necessary? Is there a way to change that?

**Comment by bhaller** [comment] 2020-05-17 00:09
Hmm.  Well, I think macOS makes this decision on the app's behalf; SLiMgui certainly isn’t requesting any particular GPU.  There may be some macOS setting you can tweak that would affect that choice, I'm not sure.  But why is it a problem?  I have a MacBook Pro, and never really notice which GPU gets chosen.

You could also try QtSLiM and see which GPU gets chosen, since it is a very different code base from SLiMgui.  But again, QtSLiM makes no specific request; it will use whatever GPU is assigned to it by the OS, I think.

Both apps might get assigned the dedicated GPU because they use OpenGL to do some of their drawing...?

**Comment by eyalbenda** [comment] 2020-05-17 00:18
The main reason for me is that I see a big impact on battery life (maybe 50% estimated in my case).  From what I understand, there is an info.plist parameter called NSSupportsAutomaticGraphicsSwitching that a developer can add to allow automatic switching, see here:
https://supermegaultragroovy.com/2016/12/10/auto-graphics-switching/ <https://supermegaultragroovy.com/2016/12/10/auto-graphics-switching/>
I’m a linux user who just moved to using a Mac, so I don’t know if this is something I can change myself.

**Comment by bhaller** [comment] 2020-05-17 01:05
It sounds like there's a third-party utility called gfxCardStatus that may let you control which GPU is used.  I have not tried this.  See this for example: https://discussions.apple.com/thread/8646824.  I'm going to close this issue since this is not a bug in SLiMgui; this behavior is up to Apple.

**Closed by bhaller** 2020-05-17 01:05 UTC

**Comment by bhaller** [comment] 2020-05-17 02:10
(I don't want to set NSSupportsAutomaticGraphicsSwitching, since SLiMgui actually does rely heavily on OpenGL and wants to get good graphics performance; I don't want to suggest otherwise to the OS.  In any case, my guess is that given how heavily SLiMgui uses OpenGL, even if I set NSSupportsAutomaticGraphicsSwitching it would probably still switch to the dedicated GPU.)

**Comment by eyalbenda** [comment] 2020-05-17 05:08
Thanks for clarifying, I'll check out that app. Thanks for developing this fantastic software!
